### ISSUE TITLE
Bug in RankALS, Q-Step

### ISSUE THREAD

**Issue by rkempter** [guoguibing/librec#10]
I used your RankALS do debug my RankALS implementation. I think I found some bug in your implementation.

If I see correctly, your \bar{A} in the Q-Step, which you named sum_cpp is equal to P^T.dot(P), but it should be P^T_{U_i}.dot(P_{U_i}). You should move it into the if-condition on r_{ui} as well.

```
if (rui > 0) {
    sum_cpp = sum_cpp.add(pp);
  sum_cpr = sum_cpr.add(pu.scale(rui));
  sum_c_sr_p = sum_c_sr_p.add(pu.scale(m_sum_sr.get(u)));
  sum_p_r_c = sum_p_r_c.add(pu.scale(rui * m_sum_c.get(u)));
}
```

**Comment by guoguibing** [comment]
Thanks for your feedback. 

After checking the code and the original paper, the code below

> DenseVector pu = P.row(u);
> double rui = trainMatrix.get(u, i);
> DenseMatrix pp = pu.outer(pu);
> sum_cpp = sum_cpp.add(pp);

says sum_cpp is the sum of p_u p_u^t, i.e., the \bar{A} in the paper. Since \bar{A} is not dependent on r_ui, I don't know why you suggest to put it in the if condition. 

What do you think?

**Comment by rkempter** [comment]
Sorry, didn't see that you responded!

It is written in the paper that \bar{A} = P_{U_i}.dot(P_{U_i}.T), the U_i means only all users that gave a rating to item i. Therefore, only if r_ui is larger than 0, meaning that we have a rating, we should add them the \bar{A}. Otherwise, you could precompute the whole matrix and don't need to do it in every item step. I added below the important section of the algorithm as an image. Hope my explanation helps.

![screen shot 2015-04-27 at 12 41 06](https://cloud.githubusercontent.com/assets/1032193/7345173/ead84ee0-ecda-11e4-9122-d172d4aeebde.png)

**Comment by guoguibing** [comment]
@466152112 @wubin7019088 what do you think?f
