### ISSUE TITLE
Why the default configuration file is to be stored by CopyOnWriteArrayList container?

### ISSUE THREAD

**Issue by wenfei13693186754** [guoguibing/librec#101]
CopyOnWriteArrayList container 不是应用于那种高并发读，读写分离的场景的吗，这里默认的配置文件不会很多的，使用这个容器会不会有点浪费空间呢？而且意义也不大呢？

**Comment by wangyufengkevin** [comment]
这个设计是方便以后分布式并发来使用的，谢谢你的建议。
