### ISSUE TITLE
a little question about your libRec frame

### ISSUE THREAD

**Issue by wenfei13693186754** [guoguibing/librec#102]
Hello, in your framework in the Configuration class, in the static code block will be the default librec.properties configuration file into the container inside, and then the user calls addResource (resource), while the default configuration file and user configuration The document was loaded, I do not understand why not in the static code block directly to the default configuration file in the information loaded into it? But to wait until loading the user profile when loading together?

**Comment by wangyufengkevin** [comment]
The variable loadDefaults will judge whether the librec-default.properties is loaded, code like Configuration(boolean loadDefaults){this.loadDefaults=loadDefaults;}, so it's loaded with user configuration together. the function hasn't developed, thanks for your attention.
