### ISSUE TITLE
Division by zero in inv() method in DenseMatrix class

### ISSUE THREAD

**Issue by abdollahpouri** [guoguibing/librec#103]
Hello, 

In the inv() method in DenseMatrix class we have:

```
if (n == 1) {
            mat.set(0, 0, 1 / this.get(0, 0));
            return mat;
        }
```
If this.get(0, 0) is zero, then we will have division by zero. 
I run the RankALS recommender for a data set and I got division by zero for some iterations. This is not handled in the code.

Thanks

**Comment by wangyufengkevin** [comment]
It's deprecated and isn't called anywhere. Thanks.

**Comment by wangyufengkevin** [comment]
If n==1 and this.get(0, 0)=0, it's a zero matrix, the zero matrix is irreversible, so it will throw RuntimeException, we'll throw a RuntimeException at here. Thanks for your issue.
