### ISSUE TITLE
Bugs in DiversityEvaluator

### ISSUE THREAD

**Issue by taolian** [guoguibing/librec#106]
@wangyufengkevin @guoguibing There is a bug in [Line 70](https://github.com/guoguibing/librec/blob/2.0.0/core/src/main/java/net/librec/eval/ranking/DiversityEvaluator.java#L70).
In my experimental results, the obtained value of the diversity measure is greater than 1.

The quantity _totalDisSimilarityPerUser_ in the numerator should not be multiplied by a factor of 2, because in the previous for loop, for each pair of distinct items _(i, j)_, we sum their dissimilarity twice into _totalDisSimilarityPerUser_, accumulating the similarities of  _topK * (topK - 1)_ pairs of items.

**Comment by KeqiangWang** [comment]
We are aware of this issue, and will correct it soon. Thank you very much
