### ISSUE TITLE
can't visit the documents

### ISSUE THREAD

**Issue by wangqi880** [guoguibing/librec#107]
![qq 20170401163833](https://cloud.githubusercontent.com/assets/7182409/24577071/b43905be-16f9-11e7-89c4-e5e4e931f76e.jpg)

i can't visit the documents~~~^_^

help~~~

**Comment by guoguibing** [comment]
Can you try it again later? This problem may be due to some issue during the page update.

**Comment by wangyufengkevin** [comment]
It's ok now, thanks for your issue.
