### ISSUE TITLE
How to invoke SVD++'s predict() functon in other algorithms

### ISSUE THREAD

**Issue by yolozhang** [guoguibing/librec#110]
For example, I want use SVD++ to predict the items' score and then use the predict score in BPR. How should I do?

**Comment by allenjack** [comment]
Hi,

It's a little confusing, can you clarify your question?

**Comment by allenjack** [comment]
Hi,
Maybe you can write the results that predicted by SVD++ to a file, then use this file as the input of BPR.

**Comment by yolozhang** [comment]
OK, thank you
