### ISSUE TITLE
how to write configuration about train-test data 

### ISSUE THREAD

**Issue by frankwhzhang** [guoguibing/librec#111]
in configuration file , for example lda-test.properties
data test file how to write

**Comment by allenjack** [comment]
Hi,

You can refer to librec-default.properties. To set the training and testing data, you need to set the path of your data, i.e., 'dfs.data.dir' and 'data.input.path'. In addition, there are several ways to set how to split the data, which is achieved by setting 'data.model.splitter'.

**Comment by LiuXiaozeeee** [comment]
@frankwhzhang Please refer to [issue#94](https://github.com/guoguibing/librec/issues/94) to get more information
