### ISSUE TITLE
TimeSVD exception

### ISSUE THREAD

**Issue by 8-chems** [guoguibing/librec#115]
using these configuration on movielens dataset
rec.recommender.class=timesvd
data.column.format=UIRT
dfs.data.dir=src/
data.input.path=ua.base
rec.iterator.learnrate=0.01
rec.iterator.learnrate.maximum=0.01
rec.iterator.maximum=13
rec.user.regularization=0.01
rec.item.regularization=0.01
rec.impItem.regularization=0.001
rec.factor.number=10
rec.learnrate.bolddriver=false
rec.learnrate.decay=1.0
 I got an exception telling 

net.librec.common.LibrecException: Loss = NaN or Infinity: current settings does not fit the recommender! Change the settings and try again!

**Comment by allenjack** [comment]
Hi,

Our initial parameter settings work well in the experiments. On different datasets, you need to carefully choose the values of parameters, since it may lead the cost function not to be optimized properly.

<img width="531" alt="screen shot 2017-04-24 at 2 58 12 pm" src="https://cloud.githubusercontent.com/assets/4423102/25353805/8e5c2f8a-28fe-11e7-9735-0f8249b075db.png">

**Comment by 8-chems** [comment]
what is this file named ratings-date.txt ??, movielens dataset is the most popular dataset, which parameters should I use ?

**Comment by allenjack** [comment]
The dataset for TimeSVD.

**Comment by 8-chems** [comment]
is there a specific values to set for movielens ?

**Comment by allenjack** [comment]
It is hard to tell, you may need to do more experiments to determine the
parameters.

**Comment by 8-chems** [comment]
thank you very much, I ll try to review the original paper, I ll share when I solve these.

**Comment by allenjack** [comment]
No problem, thank you for using LibRec. If you have any further questions, please feel free to ask.

**Comment by 8-chems** [comment]
Hey, the following values in the conf file haven't caused exception, (very low values), the data file is ua.base from 100k movielens dataset:

rec.recommender.class=timesvd
data.column.format=UIRT
dfs.data.dir=src/
data.input.path=ua.base
rec.iterator.learnrate=0.0001
rec.iterator.learnrate.maximum=1
rec.iterator.maximum=100
rec.user.regularization=0.0001
rec.item.regularization=0.0001
rec.learnrate.decay=0.00001

**Comment by allenjack** [comment]
Thank you for your effort.
