### ISSUE TITLE
Using librec 2.0

### ISSUE THREAD

**Issue by hdi-amiri** [guoguibing/librec#116]
This may be a very simple question to some but it is hard for me ! How can I use librec v2.0 , I mean imagine I have a very simple project in IntelliJIDEA and I want to use librec for implementing my thesis algorithms by help of great data structures and utility functions based on implemented algorithms?

**Comment by allenjack** [comment]
Hi,
There is an example on our GitHub home page that you can refer to. https://github.com/guoguibing/librec#code-snippet

**Comment by hdi-amiri** [comment]
Should I copy and paste all the classes and files in librec inside my project to be able to use them? or there is some jar file which I can import to my project? I guess what you are assuming is that all the files and classes of librec are inside my project, am I right?

**Comment by allenjack** [comment]
Yes, you are right. I will discuss with my teammates about the best way to use LibRec in another project and response you later.

**Comment by allenjack** [comment]
I suggest that you can either use the librec-coe.jar which is under the 'lib' directory or utilize the maven configurations which is shown bellow. 
<img width="357" alt="screen shot 2017-04-27 at 11 34 38 am" src="https://cloud.githubusercontent.com/assets/4423102/25491294/8d070e20-2b3d-11e7-8783-de27853cdcc2.png">
