### ISSUE TITLE
can not run social recommender 

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#117]
hi;
iam geting error ;
end can not run social recommender 
![2](https://cloud.githubusercontent.com/assets/28094374/25478592/056868e6-2b57-11e7-8fb7-978ffb235144.PNG)
![ss](https://cloud.githubusercontent.com/assets/28094374/25478593/05990708-2b57-11e7-8e0c-69176c98e0e4.PNG)

**Comment by guoguibing** [comment]
I think you need to specify the path of your social data.

**Comment by hphphphphp** [comment]
i want a sample code for run social recommender in librec.....thanks

**Comment by hphphphphp** [comment]
i want a sample code for run social recommender in librec.....thanks

**Comment by allenjack** [comment]
Hi,
You need to set the path of an Appender explicitly, which is used to load the social relation data. Here is an example:
<img width="305" alt="screen shot 2017-04-27 at 10 21 01 am" src="https://cloud.githubusercontent.com/assets/4423102/25487812/4dc0a55a-2b33-11e7-8188-02881c38db3f.png">

**Comment by hphphphphp** [comment]
i set the path  ...but do not solve problem.....Please check it produces an error....thank
[mycode.txt](https://github.com/guoguibing/librec/files/962452/mycode.txt)

**Comment by allenjack** [comment]
What is the problem about? Could you provide the full problem trace?
And I guess the "dfs.data.dir" should be "./data" rather than "../data".

**Comment by hphphphphp** [comment]
my code run for cf very good...but for social recommender product  error.....
for social recommender  (Rcommender   or    SocialRecommender)....
![ww](https://cloud.githubusercontent.com/assets/28094374/25517846/6f385cc2-2c06-11e7-9604-10d98d4cd250.PNG)

**Comment by allenjack** [comment]
It should be the first one. And I will test your code later.

**Comment by allenjack** [comment]
I modified some parts of your code. Now it works well on my machine.
[mycode_revised.txt](https://github.com/guoguibing/librec/files/965805/mycode_revised.txt)
