### ISSUE TITLE
use  my algorithm  from function in librec

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#120]
hi;
how to using   my algorithm from function in librec;
i want use from function (rmse-mae....) for my algorithm
i want set my config on my algorithm by librec functions 
i want use from function in librec by simplest method;

Thank you very much

**Comment by allenjack** [comment]
Please refer to this issue. https://github.com/guoguibing/librec/issues/116

**Comment by hphphphphp** [comment]
This is not .... I .... I want to test my algorithm with librec functions ....please give me a complete sample code
for this.....
want test my algorithm that wrote an me...
for example ....algorithm xyz that not exist in librec

**Comment by hphphphphp** [comment]
please guide me step by step.....very precise
thanks

**Comment by guoguibing** [comment]
It's better to read through the LibRec documentation: http://wiki.librec.net/doku.php
