### ISSUE TITLE
Trouble getting started with librec

### ISSUE THREAD

**Issue by hdi-amiri** [guoguibing/librec#121]
I have added librec via maven to my project, here is my folder structure: 

![image](https://cloud.githubusercontent.com/assets/10879511/25679282/176e9ba4-3062-11e7-84cd-62d35f38f388.png)

I have this config file:

```
data.input.path=filmtrust
data.column.format=UIR
data.model.splitter=ratio
data.convertor.format=text
data.model.format=textmodel
ratio.data.splitter=ratingratio

dfs.data.dir=data/
dfs.result.dir=result
dfs.log.dir=data/log
data.splitter.ratio=0.8
data.splitter.cv.number=5

rec.eval.auc.dropped.nums=10
rec.similarity.class=pcc
rec.neighbors.knn.number=50
rec.recommender.class=net.librec.recommender.cf.UserKNNRecommender
rec.similarity.category=true
rec.recommender.isranking=false
rec.filter.class=net.librec.filter.GenericRecommendedFilter
rec.recommender.ranking.top=0
rec.eval.enable=true
rec.eval.class=net.librec.eval.rating.MAEEvaluator
```

and this is my Driver file: 

```
import net.librec.common.LibrecException;
import net.librec.conf.Configuration;
import net.librec.job.RecommenderJob;
import net.librec.math.algorithm.Randoms;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;


public class Driver {

    private static String CONFIG_FILE = "conf/item_knn.properties";

    public static void main(String[] args) throws IOException, ClassNotFoundException, LibrecException {


        Configuration conf = new Configuration();
        String confFilePath = CONFIG_FILE;
        Properties prop = new Properties();
        prop.load(new FileInputStream(confFilePath));

        for(String name : prop.stringPropertyNames()) {
            conf.set(name, prop.getProperty(name));
        }

        Randoms.seed(20161205);

        RecommenderJob job = new RecommenderJob(conf);
        job.runJob();
        System.out.println("Finished");
    }
}
```

I am getting this exception:

![image](https://cloud.githubusercontent.com/assets/10879511/25679386/65056aaa-3062-11e7-82e5-a6dd22f52166.png)

any Idea  on what I am doing wrong?

**Comment by allenjack** [comment]
Have you debugged it?

**Comment by wangyufengkevin** [comment]
Please change data.model.format=textmodel to data.model.format=text. Detailed configuration please see here http://wiki.librec.net/doku.php?id=DataModel

**Comment by hdi-amiri** [comment]
I finally manged to get it run with this config file but I have no idea what I have done !
`
data.input.path=filmtrust
data.column.format=UIR
data.model.splitter=ratio
data.convertor.format=text
data.model.format=text
ratio.data.splitter=ratingratio
dfs.data.dir=data/
dfs.result.dir=result
dfs.log.dir=data/log
rec.similarity.class=pcc
rec.neighbors.knn.number=50
rec.recommender.similarities=user
rec.recommender.isranking=false
rec.recommender.ranking.topn=10
rec.similarity.shrinkage=10
rec.recommender.class=net.librec.recommender.cf.UserKNNRecommender
rec.filter.class=net.librec.filter.GenericRecommendedFilter
rec.eval.enable=true
rec.eval.class=net.librec.eval.rating.MAEEvaluator
`

Honestly I find it really hard to set up a simple recommender, I was wondering how hard it would be to implement my own algorithms :), just kidding :)

I really appreciate the work you guys have done.

**Comment by RichardHGL** [comment]
您好！我在处理较大的文件时遇到了问题。
我用的是自己给训练集和测试集，训练集600M，测试集3G左右。运行时报错
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
![default](https://cloud.githubusercontent.com/assets/20337906/25858725/0400e50c-350f-11e7-9f01-15c887e555b9.png)
不知道是不是应该把数据集切分更细再处理，document里没有这方面参数，所以要自己创建工程来引用这些类做处理吗

**Comment by RichardHGL** [comment]
run with userknn model, I met this Excption:
![default](https://cloud.githubusercontent.com/assets/20337906/25859312/b929be3a-3510-11e7-886b-882c2e0ea6e6.png)
the conf is:
`dfs.data.dir=../data
dfs.result.dir=../result
data.input.path=Train_file
data.column.format=UIRT
data.model.splitter=testset
data.testset.path=Test_file
data.model.format=text
rec.random.seed=1
data.convert.binarize.threshold=-1.0
rec.eval.enable=true
rec.recommender.isranking=true
`
`rec.similarity.class=pcc
rec.neighbors.knn.number=50
rec.recommender.class=userknn
rec.recommender.similarities=user
rec.recommender.isranking=true
rec.recommender.ranking.topn=10
rec.filter.class=generic
rec.similarity.shrinkage=10`

I guess maybe the trainset and testset is too large. trainset 600M, testset 3G. So how can I get it done?
