### ISSUE TITLE
RMSE of EALSRecommender bigger than 3.0

### ISSUE THREAD

**Issue by jessefilipemorais** [guoguibing/librec#122]
Hello, guys, i am need a help of you. I am testing EALSRecommender with a dataset of MovieLens but i'm not getting am RMSE smaller than 3.0.

I changed the parameters iterator and the ratio, but i have not sucess.

What more parameters can i change?

Thanks.

**Comment by KeqiangWang** [comment]
HI, EALSRecommender is used for ranking(top n recommender), so you should use ranking measures, such as precision, recall. RMSE is used for rating prediction.

Thanks

**Comment by jessefilipemorais** [comment]
Oh yes. very good. i don't observe this detail. And about precision, when de coeficient close to 0 is better? IS the same idea of RMSE, when more closer to 0, better?

Thanks.

**Comment by allenjack** [comment]
The higher of precision, the better.
