### ISSUE TITLE
Implementing algorithms with distrust.

### ISSUE THREAD

**Issue by hdi-amiri** [guoguibing/librec#123]
Hi !
I would like to implement recommenders with distrust relations, for start I would like to implement the following paper [Learning to recommend with trust and distrust](https://pdfs.semanticscholar.org/271a/06bc0900f28f288dea018507606bdc4d1b3f.pdf), how should I use librec for my purpose?

**Comment by guoguibing** [comment]
1. Choose a proper abstract recommender interface; 
+ If not, you may implement a new interface
+ Possibly, use Data Appender to lead additional trust/distrust information
2. Initialize your model by implementing setup();
+ Variable initialization
+ Pre-computing variables
3. Build your model by implementing trainModel(); 
+ Realize your algorithm logic
4. Generate a prediction by implementing predict(); 

Most importantly, read through the documentation: http://wiki.librec.net/doku.php
