### ISSUE TITLE
RMSE AND MAE   is not fixed FOR ALGORITHMS

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#125]
Hi;
Why every time a number for error and  is not fixed.
.........................
RMSE:6.264982043070834
MAE:4.25
...........................
RMSE:1.264982043070834
MAE:2.25
.............................
RMSE:8.264982043070834
MAE:0.25
..............................
RMSE:12.264982043070834
MAE:4.25

**Comment by hphphphphp** [comment]
How I fixed number of error for algorithms

**Comment by hphphphphp** [comment]
Hi;
Why every time a number for error and is not fixed.
How I fixed number of error for algorithms
.........................
RMSE:6.264982043070834
MAE:4.25
...........................
RMSE:1.264982043070834
MAE:2.25
.............................
RMSE:8.264982043070834
MAE:0.25
..............................
RMSE:12.264982043070834
MAE:4.25

**Comment by allenjack** [comment]
Hi,

Can you clarify your problem?

**Comment by hphphphphp** [comment]
I am run a algorithm...  but ... My answer to rmse  and  mae is different ..
for example :
.........................First Run :
RMSE:6.264982043070834
MAE:4.25
...........................secound run :
RMSE:1.264982043070834
MAE:2.25
.............................Third run :
RMSE:8.264982043070834
MAE:0.25
..............................
RMSE:12.264982043070834
MAE:4.25

**Comment by hdi-amiri** [comment]
can you provide your config file? which dataset/algorithm do you use?
