### ISSUE TITLE
Why no result write when isranking=false && data.model.splitter=testset?

### ISSUE THREAD

**Issue by RichardHGL** [guoguibing/librec#126]
I use` ./librec rec -exec -conf ../conf/itemknn-test.properties` to run librec on linux, but it finished without result write, why? Can I change some parameter to make it write result(prediction result)?
My properties file as follow:

librec.properties:
```
dfs.data.dir=../data/filter_data
dfs.result.dir=../result
data.input.path=ml-2m.train.rating
data.column.format=UIRT
data.model.splitter=testset
data.testset.path=test_0.txt
data.model.format=text
rec.random.seed=1
data.convert.binarize.threshold=-1.0
rec.eval.enable=false
rec.recommender.isranking=false
```
itemknn-test.properties：
```
rec.recommender.class=itemknn
rec.recommender.isranking=false
rec.recommender.ranking.topn=50

rec.recommender.similarities=item
rec.similarity.class=pcc
rec.neighbors.knn.number=50
rec.similarity.shrinkage=10
```

**Comment by RichardHGL** [comment]
I found sth strange in the source code of AbstractDataModel.java
```
if (trainDataSet != null && trainDataSet.size() > 0 && testDataSet != null && testDataSet.size() > 0) {
            LOG.info("Data size of training is " + trainDataSet.size());
            LOG.info("Data size of testing is " + testDataSet.size());
        }
```
There should be a log of trainsetsize and testsetsize, but I see my own log, it doesn't print this. Is there any error with my dataset:
both trainset and testset with UIRT
and '\t' as Interval symbol。
Looking forward to your answer.

**Comment by LiuXiaozeeee** [comment]
@RichardHGL '\t'是可以被分割的，可以把dfs.data.dir改成绝对路径试试。

**Comment by free-qc** [comment]
@LiuXiaozeeee 你好，这个testset的splitter到底是怎么运作的？不是使用我指定的文件作为测试集么？
我想用我自己分割好的数据集作为测试集和训练集

**Comment by vgeek-z** [comment]
@free-qc 根据我的理解,是先导入所有数据,包括trainSet 和 testSet, 构成一个全集; 然后再一次导入testSet, 并从全集中去除testSet中包含的数据从而建立trainSet. 这样就有了trainSet和testSet.
