### ISSUE TITLE
net.librec.job.RecommenderJob executeEvaluator reports zero values 

### ISSUE THREAD

**Issue by hdi-amiri** [guoguibing/librec#127]
If I use a separate testset for my recommender, librec reports 0 for MAE,RMSE , ... but If I use k-fold cross validation without separate test set, it works fine.

here is my sample config:
dfs.data.dir=data/netflix
dfs.result.dir=result
data.input.path=train_vec.txt
data.testset.path=probe_vec.txt
data.column.format=UIR
data.model.splitter=testset
data.splitter.ratio=rating
data.model.format=text
data.splitter.trainset.ratio=0.5
rec.random.seed=1
data.convert.binarize.threshold=-1.0
rec.eval.enable=true
rec.recommender.isranking=false
rec.recommender.class=com.hadi.BiasedMfRecommender
rec.iterator.learnrate=0.01
rec.iterator.learnrate.maximum=0.01
rec.iterator.maximum=50
rec.user.regularization=0.01
rec.item.regularization=0.01
rec.bias.regularization=0.01
rec.factor.number=2
rec.learnrate.bolddriver=false
rec.learnrate.decay=1.0

**Comment by allenjack** [comment]
Hi,
Did you check that you read the test set properly?

**Comment by hdi-amiri** [comment]
yes I checked that too, here is my output for ml-100k dataset with ua.base and ua.test:

May 23, 2017 1:43:52 AM net.librec.data.convertor.TextDataConvertor readData
INFO: Dataset: data/movielens/ml-100k/ua.base
May 23, 2017 1:43:52 AM net.librec.data.convertor.TextDataConvertor readData
INFO: All dataset files [data\movielens\ml-100k\ua.base]
May 23, 2017 1:43:52 AM net.librec.data.convertor.TextDataConvertor readData
INFO: All dataset files size 1792501
May 23, 2017 1:43:52 AM net.librec.data.convertor.TextDataConvertor readData
INFO: Now loading dataset file ua
May 23, 2017 1:43:54 AM net.librec.data.model.TextDataModel buildDataModel
INFO: Transform data to Convertor successfully!
May 23, 2017 1:43:54 AM net.librec.data.convertor.TextDataConvertor readData
INFO: Dataset: data/movielens/ml-100k/ua.test
May 23, 2017 1:43:54 AM net.librec.data.convertor.TextDataConvertor readData
INFO: All dataset files [data\movielens\ml-100k\ua.test]
May 23, 2017 1:43:54 AM net.librec.data.convertor.TextDataConvertor readData
INFO: All dataset files size 186672
May 23, 2017 1:43:54 AM net.librec.data.convertor.TextDataConvertor readData
INFO: Now loading dataset file ua
May 23, 2017 1:43:54 AM net.librec.data.model.TextDataModel buildDataModel
INFO: Split data to train Set and test Set successfully!

**Comment by ThiagoSousa** [comment]
I'm having the same problem with the same dataset. I guess it is a bug that it doesn't calculate the metrics for testset split option.

**Comment by SunYatong** [comment]
@ThiagoSousa
Make sure that "data.input.path" includes all data files you want to read, and "data.testset.path" should be a sub-directory of "data.input.path", which specifies the files you want to read into testset.

for example:
```java
		conf.set("data.input.path", "test/given-testset");
		conf.set("data.testset.path", "test/given-testset/test");
```
