### ISSUE TITLE
Which algorithm is user-based collaborative filtering algorithm

### ISSUE THREAD

**Issue by xiexiaomiao** [guoguibing/librec#129]

**Comment by guoguibing** [comment]
UserKNN

**Comment by xiexiaomiao** [comment]
Is this only one?

**Comment by allenjack** [comment]
In the literature, user-based CF sometimes refers to UserKnn. There is a book--Collaborative Filtering Recommender Systems written by Michael D. Ekstrand et al. that you can make a reference.

**Comment by xiexiaomiao** [comment]
Thank you

**Comment by xiexiaomiao** [comment]
I do not know much about these，thank you for your help
