### ISSUE TITLE
Some evaluators not being used

### ISSUE THREAD

**Issue by T-10001** [guoguibing/librec#130]
Ran all the algorithms with rec.eval.classes blank. Which means it should run all the related evaluators, but idcg, arhr, diversity and hitrate never run.

Also diversity gets NullPointerException.

> Exception in thread "main" java.lang.NullPointerException
>         at net.librec.eval.ranking.DiversityEvaluator.evaluate(DiversityEvaluator.java:52)
>         at net.librec.eval.AbstractRecommenderEvaluator.evaluate(AbstractRecommenderEvaluator.java:68)
>         at net.librec.recommender.AbstractRecommender.evaluate(AbstractRecommender.java:340)
>         at net.librec.job.RecommenderJob.executeEvaluator(RecommenderJob.java:221)
>         at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:145)
>         at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:122)
>         at net.librec.tool.driver.RecDriver.run(RecDriver.java:84)
>         at net.librec.tool.driver.RecDriver.main(RecDriver.java:111)

**Comment by allenjack** [comment]
Hi,
It depends on what kinds of algorithms your are running. If you are running a rating algorithm, rating metrics such as RMSE and MAE will be performed; if you are conducting a ranking algorithm, ranking metrics will be applied, such as Precision, Recall.

**Comment by T-10001** [comment]
But I have tried all the inbuilt algorithms. So none of them use those 4 metrics?

**Comment by allenjack** [comment]
Actually, you can specify which evaluation metric to use.

**Comment by T-10001** [comment]
Yes, and I chose to leave specification blank which should then make it use all the metrics it can. But those 4 never get used. That is the problem.

**Comment by allenjack** [comment]
Hi,
Rating and ranking are two tasks that we focus on, thus the metrics about rating and ranking will be applied without specification.

**Comment by T-10001** [comment]
What do you mean by that? Are the 4 evaluators I mentioned not about rating or ranking?
So I have to manually specify them?

**Comment by allenjack** [comment]
Yes, you are right.
