### ISSUE TITLE
Question about data.model.splitter

### ISSUE THREAD

**Issue by free-qc** [guoguibing/librec#131]
I'm confused about the **testset** data splitter. I wanna use my own dataset i'v prepared as test set,  but when i set data splitter to testset, librec still splits the dataset into train set and test set. 
So how exactly does testset data splitter work?

**Comment by allenjack** [comment]
Hi,
It sounds wired. Could you debug it and make sure you set the configuration
properly?

**Comment by free-qc** [comment]
This is my properties

rec.similarity.class=pcc
rec.neighbors.knn.number=50
rec.recommender.class=userknn
rec.recommender.similarities=user

rec.recommender.isranking=flase
rec.recommender.ranking.topn=10
rec.filter.class=generic
rec.similarity.shrinkage=1

dfs.data.dir=../data/stock
dfs.result.dir=../result
data.input.path=train.txt
data.column.format=UIR

data.model.splitter=testset
data.testset.path=test.txt
data.model.format=text

rec.random.seed=1
data.convert.binarize.threshold=-1.0

rec.eval.enable=true

rec.eval.classes=precision,recall
rec.recommender.isranking=false

and this is the result

qc-MBP:bin qc$ bash librec rec -exec -conf test.properties
17/05/19 15:00:44 INFO TextDataConvertor: Dataset: ../data/stock/train.txt
17/05/19 15:00:44 INFO TextDataConvertor: All dataset files [../data/stock/train.txt]
17/05/19 15:00:44 INFO TextDataConvertor: All dataset files size 1847046
17/05/19 15:00:44 INFO TextDataConvertor: Now loading dataset file train
17/05/19 15:00:45 INFO TextDataModel: Transform data to Convertor successfully!
17/05/19 15:00:45 INFO TextDataConvertor: Dataset: ../data/stock/test.txt
17/05/19 15:00:45 INFO TextDataConvertor: All dataset files [../data/stock/test.txt]
17/05/19 15:00:45 INFO TextDataConvertor: All dataset files size 2157664
17/05/19 15:00:45 INFO TextDataConvertor: Now loading dataset file test
17/05/19 15:00:46 INFO TextDataModel: Split data to train Set and test Set successfully!
17/05/19 15:00:46 INFO TextDataModel: Data size of training is 86231
17/05/19 15:00:46 INFO TextDataModel: Data size of testing is 52775
17/05/19 15:00:59 INFO UserKNNRecommender: Job Setup completed.
17/05/19 15:00:59 INFO UserKNNRecommender: Job Train completed.
17/05/19 15:01:29 INFO UserKNNRecommender: Job End.
17/05/19 15:01:29 INFO RecommenderJob: Evaluator info:PrecisionEvaluator is 0.30568969639012294
17/05/19 15:01:29 INFO RecommenderJob: Evaluator info:RecallEvaluator is 0.9546266201484228
17/05/19 15:01:29 INFO RecommenderJob: Result path is ../result/train.txt-userknn-output/userknn
Finished

it loads all of the dataset files, but why librec still splits the data?
And it's the same result when I run librec in IDE.

**Comment by allenjack** [comment]
It seems that it runs smoothly. Have you checked that if the split test set
has the same size with your original test set?

And I suggest that you can debug it line by line and see if it uses the
right splitter.
