### ISSUE TITLE
TrustPMF implementation

### ISSUE THREAD

**Issue by hdi-amiri** [guoguibing/librec#135]
Hi
I want to implement [this ](http://ieeexplore.ieee.org/document/7558226/) algorithm with librec(IEEE TrustPMF), I have written the following code for this algorithm:
`

        
        import net.librec.common.LibrecException;
        import net.librec.math.algorithm.Maths;
        import net.librec.math.structure.DenseMatrix;
        import net.librec.math.structure.DenseVector;
        import net.librec.math.structure.MatrixEntry;
        import net.librec.recommender.SocialRecommender;
        
        public class TrustPMF extends SocialRecommender {
        
            protected double lambda;
            protected double beta1, beta2;
            protected DenseMatrix userTrusterFactors, userTrusteeFactors;
            protected DenseVector userWeights, itemWeights, trusterWeights, trusteeWeights;
        
            @Override
            public void setup() throws LibrecException {
                super.setup();
        
                userTrusteeFactors = new DenseMatrix(numUsers, numFactors);
                userTrusterFactors = new DenseMatrix(numUsers, numFactors);
        
                userWeights = new DenseVector(numUsers);
                itemWeights = new DenseVector(numItems);
                trusterWeights = new DenseVector(numUsers);
                trusteeWeights = new DenseVector(numUsers);
        
                userWeights.init();
                itemWeights.init();
                trusteeWeights.init();
                trusteeWeights.init();
        
                for (int u = 0; u < numUsers; u++) {
                    int ratedItemCount = trainMatrix.rowSize(u);
                    int trustedCount = socialMatrix.rowSize(u);
                    int truseeCount = socialMatrix.columnSize(u);
        
                    if (ratedItemCount > 0) {
                        userWeights.set(u, ratedItemCount);
                    } else {
                        userWeights.set(u, 1);
                    }
        
                    if (trustedCount > 0) {
                        trusterWeights.set(u, trustedCount);
                    } else {
                        trusterWeights.set(u, 1);
                    }
        
        
                    if (truseeCount > 0) {
                        trusteeWeights.set(u, truseeCount);
                    } else {
                        trusteeWeights.set(u, 1);
                    }
                }
        
                for (int itemIdx = 0; itemIdx < numItems; itemIdx++) {
                    int ratedUserCount = trainMatrix.columnSize(itemIdx);
                    if (ratedUserCount > 0) {
                        itemWeights.set(itemIdx, ratedUserCount);
                    } else {
                        itemWeights.set(itemIdx, 1);
                    }
                }
        
        
                userTrusterFactors.init();
                userTrusteeFactors.init();
        
                lambda = conf.getDouble("rec.regularization");
                beta1 = conf.getDouble("rec.beta1");
                beta2 = conf.getDouble("rec.beta2");
            }
        
            @Override
            protected void trainModel() throws LibrecException {
                for (int iter = 1; iter <= numIterations; iter++) {
                    loss = 0.0d;
        
                    DenseMatrix userTrusterGradients = new DenseMatrix(numUsers, numFactors);
                    DenseMatrix userTrusteeGradents = new DenseMatrix(numUsers, numFactors);
                    DenseMatrix itemGradients = new DenseMatrix(numItems, numFactors);
                    DenseMatrix userGradients = new DenseMatrix(numUsers, numFactors);
        
                    for (MatrixEntry matrixEntry : trainMatrix) {
                        int userIdx = matrixEntry.row();
                        int itemIdx = matrixEntry.column();
                        double rating = matrixEntry.get();
        
                        double predictedRating = predict(userIdx, itemIdx, false);
        
                        double error = Maths.logistic(predictedRating) - normalize(rating);
        
                        loss += error * error;
        
                        double deriValue = Maths.logisticGradientValue(predictedRating) * error;
        
                        for (int factorIdx = 0; factorIdx < numFactors; factorIdx++) {
        
                            double itemFactorValue = itemFactors.get(itemIdx, factorIdx);
                            double userFactorValue = userFactors.get(userIdx, factorIdx);
                            double trusterFactorValue = userTrusterFactors.get(userIdx, factorIdx);
                            double trusteeFactorValue = userTrusteeFactors.get(userIdx, factorIdx);
        
        
                            userGradients.add(userIdx, factorIdx,
                                    deriValue * itemFactorValue +
                                            lambda * userWeights.get(userIdx) * userFactorValue +
                                            beta1 * (userFactorValue - trusterFactorValue) +
                                            beta2 * (userFactorValue - trusteeFactorValue));
        
                            itemGradients.add(itemIdx, factorIdx,
                                    deriValue * userFactorValue +
                                            lambda * itemWeights.get(itemIdx) * itemFactorValue);
                        }
                    }
        
        
                    for (MatrixEntry matrixEntry : socialMatrix) {
                        int userIdx = matrixEntry.row();
                        int userSocialIdx = matrixEntry.column();
                        double socialValue = matrixEntry.get();
        
                        if (socialValue > 0) {
                            double predictedSocialValue = DenseMatrix.rowMult(userTrusterFactors, userIdx, userTrusteeFactors, userSocialIdx);
                            double socialError = Maths.logistic(predictedSocialValue) - normalize(socialValue);
        
        
                            loss += socialError * socialError;
        
                            double deriValue = Maths.logisticGradientValue(predictedSocialValue) * socialError;
        
                            for (int factorIdx = 0; factorIdx < numFactors; factorIdx++) {
                                double trusterFactor = userTrusterFactors.get(userIdx, factorIdx);
                                double trusteeFactor = userTrusteeFactors.get(userSocialIdx, factorIdx);
                                double userTrusterFactor = userFactors.get(userIdx, factorIdx);
                                double userTrusteeFactor = userFactors.get(userSocialIdx, factorIdx);
        
        
                                userTrusterGradients.add(deriValue * trusteeFactor -
                                        beta1 * (userTrusterFactor - trusterFactor) +
                                        lambda * trusterWeights.get(userIdx) * trusterFactor);
        
        
                                userTrusteeGradents.add(deriValue * trusterFactor -
                                        beta2 * (userTrusteeFactor - trusteeFactor) +
                                        lambda * trusteeWeights.get(userSocialIdx) * trusteeFactor);
        
                            }
                        }
                    }
        
                    loss += computeRegularizationLoss();
        
                    userTrusteeFactors.addEqual(userTrusteeGradents.scale(-1 * learnRate));
                    userTrusterFactors.addEqual(userTrusterGradients.scale(-1 * learnRate));
                    userFactors.addEqual(userGradients.scale(-1 * learnRate));
                    itemFactors.addEqual(itemGradients.scale(-1 * learnRate));
        
        
                    loss *= 0.5d;
        
                    if (isConverged(iter) && earlyStop) {
                        break;
                    }
        
                    updateLRate(iter);
        
                }
            }
        
            private double computeRegularizationLoss() {
                double loss = 0.0d;
        
                for (int u = 0; u < numUsers; u++) {
                    for (int factorIdx = 0; factorIdx < numFactors; factorIdx++) {
        
                        double userFactor = userFactors.get(u, factorIdx);
                        double trusterFactor = userTrusterFactors.get(u, factorIdx);
                        double trusteeFactor = userTrusteeFactors.get(u, factorIdx);
        
                        loss += lambda * userFactor * userFactor +
                                beta1 * (userFactor - trusterFactor) * (userFactor - trusterFactor) +
                                beta2 * (userFactor - trusteeFactor) * (userFactor - trusteeFactor) +
                                lambda * trusterFactor * trusterFactor +
                                lambda * trusteeFactor * trusteeFactor;
                    }
                }
        
                for (int i = 0; i < numItems; i++) {
                    for (int factorIdx = 0; factorIdx < numFactors; factorIdx++) {
                        double itemFactor = itemFactors.get(i, factorIdx);
        
                        loss += lambda * itemFactor * itemFactor;
                    }
                }
        
                return loss;
            }
        
            @Override
            protected double predict(int userIdx, int itemIdx) {
                double rating = denormalize(DenseMatrix.rowMult(userFactors, userIdx, itemFactors, itemIdx));
        
                if (rating > 5)
                    return 5.0;
                if (rating < 1)
                    return 1.0;
                return rating;
            }
        
            protected void updateLRate(int iter) {
                if (iter == 10)
                    learnRate *= 0.6;
                else if (iter == 30)
                    learnRate *= 0.333;
                else if (iter == 100)
                    learnRate *= 0.5;
                lastLoss = loss;
            }
        }

`

I based my implementation on TrustMF.java of librec, but with one difference, and that is computing loss, I kind of think that your way of calculating loss is wrong, for example for TrustMF we have:
`

      for (int factorIdx = 0; factorIdx < numFactors; factorIdx++) {
           double trusterUserTrusterFactorValue = trusterUserTrusterFactors.get(userIdx, factorIdx);
           double trusterUserTrusteeFactorValue = trusterUserTrusteeFactors.get(userSocialIdx, factorIdx);
        
           userTrusterGradients.add(userIdx, factorIdx, regSocial * deriValue * trusterUserTrusteeFactorValue + regUser * trusterUserTrusterFactorValue);
           userTrusteeGradients.add(userSocialIdx, factorIdx, regSocial * deriValue * trusterUserTrusterFactorValue + regUser * trusterUserTrusteeFactorValue);
        
           loss += regUser * trusterUserTrusterFactorValue * trusterUserTrusterFactorValue +
            regUser * trusterUserTrusteeFactorValue * trusterUserTrusteeFactorValue;
          }

`

I think in the above piece of code, you are adding regularization term for each instance of training input, for each (u,i) \in R, which I think should be calculated in a separate loop over all users or items. Correct me If I am wrong.

for TrustPMF algorithm I have used the following config file:

    dfs.data.dir = data / filmtrust
    dfs.result.dir = result
    data.input.path = rating
    data.column.format = UIR
    data.model.splitter = ratio
    data.splitter.ratio = rating
    data.model.format = text
    data.splitter.trainset.ratio = 0.8
    rec.random.seed = 1
    
    data.appender.class = social
    data.appender.path = trust
    
    rec.iterator.learnrate = 0.001
    rec.iterator.learnrate.maximum = 0.01
    rec.iterator.maximum = 30
    rec.factor.number = 2
    rec.learnrate.bolddriver = false
    rec.learnrate.decay = 1.0
    rec.recommender.earlystop = false
    
    rec.regularization = 0.001
    rec.beta1 = 10
    rec.beta2 = 10
    
    rec.recommender.verbose = true
    rec.recommender.class = com.hadi.TrustPMF

which gave me the following result:

    May 26, 2017 11: 39: 02 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: Dataset: data / filmtrust / rating
    May 26, 2017 11: 39: 02 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: All dataset files[data\ filmtrust\ rating\ ratings_0.txt, data\ filmtrust\ rating\ ratings_1.txt, data\ 
    filmtrust\ rating\ ratings_2.txt, data\ filmtrust\ rating\ ratings_3.txt]
    May 26, 2017 11: 39: 02 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: All dataset files size 411942
    May 26, 2017 11: 39: 02 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: Now loading dataset file ratings_0
    May 26, 2017 11: 39: 03 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: Now loading dataset file ratings_1
    May 26, 2017 11: 39: 03 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: Now loading dataset file ratings_2
    May 26, 2017 11: 39: 03 AM net.librec.data.convertor.TextDataConvertor readData
    INFO: Now loading dataset file ratings_3
    May 26, 2017 11: 39: 03 AM net.librec.data.model.TextDataModel buildDataModel
    INFO: Transform data to Convertor successfully!
     May 26, 2017 11: 39: 03 AM net.librec.data.model.TextDataModel buildDataModel
    INFO: Split data to train Set and test Set successfully!
     May 26, 2017 11: 39: 03 AM net.librec.data.model.TextDataModel buildDataModel
    INFO: Data size of training is 28408
    May 26, 2017 11: 39: 03 AM net.librec.data.model.TextDataModel buildDataModel
    INFO: Data size of testing is 7086
    May 26, 2017 11: 39: 03 AM net.librec.data.model.TextDataModel buildDataModel
    INFO: Transform data to Feature successfully!
     May 26, 2017 11: 39: 03 AM com.hadi.TrustPMF recommend
    INFO: Job Setup completed.
    May 26, 2017 11: 39: 04 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 1: loss = 11377.962205945767, delta_loss = -11377.962
    May 26, 2017 11: 39: 04 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 2: loss = 7124.742287340123, delta_loss = 4253.2197
    May 26, 2017 11: 39: 05 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 3: loss = 6704.74323813365, delta_loss = 419.99905
    May 26, 2017 11: 39: 05 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 4: loss = 11395.92501785266, delta_loss = -4691.1816
    May 26, 2017 11: 39: 06 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 5: loss = 48333.74810509593, delta_loss = -36937.824
    May 26, 2017 11: 39: 06 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 6: loss = 319795.19473478565, delta_loss = -271461.44
    May 26, 2017 11: 39: 07 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 7: loss = 2350659.4662185423, delta_loss = -2030864.2
    May 26, 2017 11: 39: 07 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 8: loss = 1.7753368827366263E7, delta_loss = -1.5402709E7
    May 26, 2017 11: 39: 08 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 9: loss = 1.355897759766982E8, delta_loss = -1.17836408E8
    May 26, 2017 11: 39: 08 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 10: loss = 1.0416003362875898E9, delta_loss = -9.0601056E8
    May 26, 2017 11: 39: 09 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 11: loss = 8.029098039073458E9, delta_loss = -6.9874975E9
    May 26, 2017 11: 39: 09 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 12: loss = 1.2903848373331306E10, delta_loss = -4.8747505E9
    May 26, 2017 11: 39: 09 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 13: loss = 2.078621137274098E10, delta_loss = -7.8823629E9
    May 26, 2017 11: 39: 10 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 14: loss = 3.353409465710801E10, delta_loss = -1.27478835E10
    May 26, 2017 11: 39: 10 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 15: loss = 5.4162204600706314E10, delta_loss = -2.06281093E10
    May 26, 2017 11: 39: 11 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 16: loss = 8.756500570625728E10, delta_loss = -3.34028001E10
    May 26, 2017 11: 39: 11 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 17: loss = 1.416953565165293E11, delta_loss = -5.4130352E10
    May 26, 2017 11: 39: 12 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 18: loss = 2.294847232146137E11, delta_loss = -8.7789363E10
    May 26, 2017 11: 39: 12 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 19: loss = 3.719771473992525E11, delta_loss = -1.42492418E11
    May 26, 2017 11: 39: 13 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 20: loss = 6.034436954172384E11, delta_loss = -2.31466549E11
    May 26, 2017 11: 39: 13 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 21: loss = 9.797400849992344E11, delta_loss = -3.76296374E11
    May 26, 2017 11: 39: 13 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 22: loss = 1.5919670560724302E12, delta_loss = -6.1222696E11
    May 26, 2017 11: 39: 14 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 23: loss = 2.588821239157883E12, delta_loss = -9.968542E11
    May 26, 2017 11: 39: 14 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 24: loss = 4.2131795949499663E12, delta_loss = -1.62435839E12
    May 26, 2017 11: 39: 15 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 25: loss = 6.862032528105577E12, delta_loss = -2.64885292E12
    May 26, 2017 11: 39: 15 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 26: loss = 1.1184714299738318E13, delta_loss = -4.32268168E12
    May 26, 2017 11: 39: 16 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 27: loss = 1.824401804320485E13, delta_loss = -7.0593036E12
    May 26, 2017 11: 39: 16 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 28: loss = 2.978058981456194E13, delta_loss = -1.15365716E13
    May 26, 2017 11: 39: 17 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 29: loss = 4.864707561503475E13, delta_loss = -1.88664848E13
    May 26, 2017 11: 39: 17 AM com.hadi.TrustPMF isConverged
    INFO: TrustPMF iter 30: loss = 7.952138730624827E13, delta_loss = -3.08743116E13
    May 26, 2017 11: 39: 17 AM com.hadi.TrustPMF recommend
    INFO: Job Train completed.
    May 26, 2017 11: 39: 17 AM com.hadi.TrustPMF recommend
    INFO: Job End.
    May 26, 2017 11: 39: 17 AM net.librec.job.RecommenderJob executeEvaluator
    INFO: Evaluator value: RMSE is 1.0417789396240704
    May 26, 2017 11: 39: 17 AM net.librec.job.RecommenderJob executeEvaluator
    INFO: Evaluator value: MPE is 1.0
    May 26, 2017 11: 39: 17 AM net.librec.job.RecommenderJob executeEvaluator
    INFO: Evaluator value: MAE is 0.7821807993548663
    May 26, 2017 11: 39: 17 AM net.librec.job.RecommenderJob executeEvaluator
    INFO: Evaluator value: MSE is 1.0853033590442525
    May 26, 2017 11: 39: 17 AM net.librec.job.RecommenderJob saveResult
    INFO: Result path is result / rating - trustpmf - output / trustpmf

What is wrong with my implementation that there is so much fluctuation in loss value?

Thanks

**Comment by allenjack** [comment]
Hi,
You'd better check your code line by line to see whether it exactly follows
the procedure of the paper.

**Comment by hdi-amiri** [comment]
Hi, 
Thanks for quick reply, my problem is about how you guys computed the value of `loss` in implementation of your algorithms, which one is correct? the one I have wrote or the one you wrote?

**Comment by Kerr19** [comment]
Do you finish the code ? if you finish,can you share it .Beacuse i have some interest in this paper ,i want to  achieve it,but i have some problem .thank you very much

**Comment by hdi-amiri** [comment]
@Kerr19  I gave up on this library years ago ! move on to something more transparent! Or implement your own !
