### ISSUE TITLE
HFTRecommender 第303行

### ISSUE THREAD

**Issue by murdonson** [guoguibing/librec#143]
SGD优化 根据公式应该是 double sgd_u = euj * qjf + regUser * puf而不是double sgd_u = euj * qjf - regUser * puf吧?

**Comment by SunYatong** [comment]
Here is my expression , sgd_u is in the red rectangle :
![issue](https://cloud.githubusercontent.com/assets/17143022/26709225/c0de1cd6-4783-11e7-9d19-3cba4d15a124.jpg)

**Comment by murdonson** [comment]
@SunYatong  Thank you!
