### ISSUE TITLE
HFTRecommender dataset

### ISSUE THREAD

**Issue by ChenSuL** [guoguibing/librec#145]
how do you generate the HFTRecommender dataset `musical_instruments_full.arff`  from the original Amazon reviews ?
What's the meaning of each line?
@DATA
0,0,5.0,0:1:2:3:4:5:6:7:0:8:9:10:11:5:4:12:13:14:15:16:17:18:11

**Comment by SunYatong** [comment]
@ChenSuL 
1. I pre-process the Amazon .json file with a python script to remove stop words and do stemming.
2. Each line means [userId,itemId,rating,review], where review is expressed as indices of words.

**Comment by ChenSuL** [comment]
OK, thanks.

**Comment by murdonson** [comment]
@SunYatong How can I get the original Amazon reviews in your librec? Please

**Comment by ChenSuL** [comment]
You can download it from here 
[](http://jmcauley.ucsd.edu/data/amazon/)

**Comment by SunYatong** [comment]
@murdonson 
Here are the original Amazon datasets : http://jmcauley.ucsd.edu/data/amazon/
In Librec we only use the musical_instruments_5_core currently.

**Comment by murdonson** [comment]
@SunYatong   I pre-process the Amazon .json file with a python script to remove stop words and do stemming.    Could you offer me the python script please? I want to do some research about this topic
