### ISSUE TITLE
Could you please implemment CoFactor(Factorization Meets the Item Embedding: Regularizing Matrix Factorization with Item Co-occurrence ACM RECSYS16) algorithm in librec

### ISSUE THREAD

**Issue by murdonson** [guoguibing/librec#147]

**Comment by murdonson** [comment]
@guoguibing  Could you please implemment CoFactor(Factorization Meets the Item Embedding: Regularizing Matrix Factorization with Item Co-occurrence ACM RECSYS16) algorithm in librec

**Comment by murdonson** [comment]
@SunYatong https://gist.github.com/murdonson/bfee3b7ef2414954d170e1fa8e74d915 I just implement Cofactor algorithm with your librec. But I am not good at coding，just a rookie.I wonder how to save SPIM matrix to a txt document so I can save a lot of time.   
![image](https://cloud.githubusercontent.com/assets/20641803/26759532/cbe61556-4932-11e7-9f22-7149d1a43989.png)

**Comment by murdonson** [comment]
@SunYatong SoRecRecommender 参考文献写错了

**Comment by SunYatong** [comment]
@murdonson 
Hi, I'm afraid didn't get your point.
- What is "SPIM matrix"? I Googled it with no relevant result.
- What is the meaning of "save SPIM matrix to a txt document so I can save a lot of time"?

I glanced over your code and the paper of CoFactor, found some problems.
- CoFactor is a ranking algorithm but you are using the rating evaluators.
- Why do you use DenseMatrix rather than DenseVector for bias variables?

**Comment by murdonson** [comment]
@SunYatong 
First,thank you for your reply. The paper is Factorization Meets the Item Embedding: Regularizing
Matrix Factorization with Item Co-occurrence.I made a mistake.It is SPPMI matrix.

![vq6bv_16pz13 bv _u78r5](https://cloud.githubusercontent.com/assets/20641803/26767650/85970b9e-49d4-11e7-8cc5-5db995068e02.png)
The construction of SPPMI matrix is time consuming with my computer. For a certain training dataset,you can construct SPPMI matrix  only once and save the matrix to hard disk.  I should use ranking evaluators.Other problems in my code,I can not fix them.I am a rookie at coding.   
Would you please correct my code?  https://github.com/murdonson/CoFactor    I think it is easy for you. Besides ,I friend you last night on wechat.
CoFactor 就比普通的MF多个item-cocurrence矩阵，实在憋不出英语了^_^，你应该能看懂中文:)

**Comment by SunYatong** [comment]
@murdonson 
Sorry, the persistence of data structures haven't been finished yet. You may convert your matrix as a table [itemidx, itemidx, value] to save and load. It should work as you need,  not elegant though...
