### ISSUE TITLE
How to use Librec other than for testing purpose using librec.conf ?

### ISSUE THREAD

**Issue by doxav** [guoguibing/librec#15]
I wonder if Librec can be tested out of the box in batch or online mode with the appropriate librec.conf (ie. without coding a dedicated Java layer to test it). So, is there any option to :
- resume/load a saved model in the librec.conf ?
- run Librec in daemon mode and send/receive data via stdin/stdout or any communication layer ?

Thank you,
Xavier

**Comment by guoguibing** [comment]
If only the built-in recommenders are tested, we do not need to write any codes but only need to prepare a proper configuration file (librec.conf), or you can specify your own files with argument "-c file1.conf file2.conf...". 

* I designed the model saving part, but i didn't implement it for most of recommenders. 
* LibRec requires a configuration file, and will write back recommendation performance to plain text file (under the folder "Results" by default), and optionally send email notification (with results as attachment) when it is done.

**Comment by guoguibing** [comment]
More information can be referred to [this tutorial](http://librec.net/tutorial.html)

**Comment by doxav** [comment]
Thanks a lot for your answer.

I think my question was a bit confusing. I looked into http://librec.net/tutorial.html and it looks like Librec is only meant for testing its own performance. My question is more: is there any way to use Librec not just for testing its own performance but for a real use case like realtime recommendation or upon request (the model would have been trained before either in batch mode or iterative). Unfortunately, and as per your first answer, if saving model is not implemented I doubt Librec can be used for a real use case ?

Thx,
Xavier

**Comment by guoguibing** [comment]
Hi Xavier, 

It is true that current version may not be suitable for a production mode. I intended to design a recommendation tool for research purpose, and I didn't consider such the demand for production. Many more efforts are required to use it in production mode, such as incremental update, better large-scale design, etc. LibRec is far from perfect now, and personally I don't have dedicated time to do so. 

Hope more experts join and further polish it.

**Comment by doxav** [comment]
Hi, Thanks for your feedback. I wouldn't have really used in production mode but first would have tested a small prototype to compare it to what I already use. Then if it's promising, it would be worth to invest time to make it usable in production. Without save/resume model options to do a minimal prototype (even without incremental update after resume), I think it will be hard to get many non academic people to test it. I hope I am wrong because it's a very promising project. Regards, Xavier

**Comment by guoguibing** [comment]
Hi Xavier, 

Thanks for your good suggestion. We'll put efforts in our next version to enable the model saving and resuming functionality. For the time being, you can set up a configuration file to test if LibRec provides promising results. There is a demo under the folder "demo" along with the example configuration files.

**Comment by doxav** [comment]
Thanks Guo for taking time to answer. I reviewed your demo, your work is impressive. I will definitely follow your repo. Xavier

**Comment by anslaity** [comment]
hi,

I'm trying to access the aforementioned tutorial page (https://www.librec.net/tutorial.html) but the browser shows me that this page is no longer exist. Do you have more resources and tutorials? I'm looking for something to implement and evaluate ANY recommender (i.e. my goal is the evaluation not the recommender itself).

Thanks

**Comment by SunYatong** [comment]
@anslaity 
Hi, Our documentation (https://www.librec.net/dokuwiki/doku.php) should be helpful for you.

**Comment by lorddubbs** [comment]
Hi, i have read the docs but is it possible to integrate Librec with a web app using REST service or a command line process say with a web technology like Rails or Laravel ?
