### ISSUE TITLE
how to... access to SimilarityMatrix

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#154]
hi;
how to... access to SimilarityMatrix  and put its  in the  DenseMatrix  or put its in the array??
for example ...sim(u1,u2)=???
my code is :
![1](https://user-images.githubusercontent.com/28094374/26926141-a21c46be-4c61-11e7-9360-9dc80c715623.PNG)

**Comment by hphphphphp** [comment]
and error of this code :
![1](https://user-images.githubusercontent.com/28094374/26926241-26a78308-4c62-11e7-85bb-e3d2d096d672.PNG)

**Comment by hphphphphp** [comment]
how to compute  similarity bettwen users.......sim(u1,u2)=???

**Comment by SunYatong** [comment]
@hphphphphp 
Hi, you should use the "get(int row, int col)" function of the SymmMaitrx to get entries' values.
```java
        // build similarity
        RecommenderSimilarity similarity = new PCCSimilarity();
        similarity.buildSimilarityMatrix(dataModel);

        // get similarity values
        int numUser = ((SparseMatrix)dataModel.getTrainDataSet()).numRows();
        SymmMatrix similarityMatrix = similarity.getSimilarityMatrix();

        for (int i=0; i<numUser; i++) {
            for (int j=0; j<numUser; j++) {
                System.out.println("user_" + i + ", user_" + j + ", similarity: " + similarityMatrix.get(i, j));
            }
        }
```

**Comment by hphphphphp** [comment]
hi;
why ...similarityMatrix.get(i, j)....   Produces Different values for each iteration???

for example  :
first run :
user_0, user_0, similarity: 0.0
user_0, user_1, similarity: 0.9999999999999998
user_0, user_2, similarity: 0.9999999999999998
user_0, user_3, similarity: 0.9999999999999998
user_1, user_0, similarity: 0.9999999999999998
user_1, user_1, similarity: 0.0
user_1, user_2, similarity: 0.9999999999999998
user_1, user_3, similarity: 0.0
user_2, user_0, similarity: 0.9999999999999998
user_2, user_1, similarity: 0.9999999999999998
user_2, user_2, similarity: 0.0
user_2, user_3, similarity: 0.0

*************************
second run :
user_0, user_0, similarity: 0.0
user_0, user_1, similarity: 0.9999999999999998
user_0, user_2, similarity: 0
user_0, user_3, similarity: 0.9999999999999998
user_1, user_0, similarity: 0.9999999999999998
user_1, user_1, similarity: 0.0
user_1, user_2, similarity: 0.9999999999999998
user_1, user_3, similarity: 0
user_2, user_0, similarity: 0.9819805060619659
user_2, user_1, similarity: 0.9999999999999998
user_2, user_2, similarity: 0.0
user_2, user_3, similarity: 0.9999999999999998
*****************************
third run
user_0, user_0, similarity: 0.0
user_0, user_1, similarity: 0.9999999999999998
user_0, user_2, similarity: 0.9819805060619659
user_0, user_3, similarity: 0.9999999999999998
user_1, user_0, similarity: 0.9999999999999998
user_1, user_1, similarity: 0.0
user_1, user_2, similarity: 0.0
user_1, user_3, similarity: 0.0
user_2, user_0, similarity: 0.9819805060619659
user_2, user_1, similarity: 0.0
user_2, user_2, similarity: 0.0

**Comment by SunYatong** [comment]
@hphphphphp 
Fix the random seed at beginning if you want reproducible results.
```java
        Randoms.seed(1);
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();
        ......

```
