### ISSUE TITLE
Multithreaded Matrix Multiplication

### ISSUE THREAD

**Issue by ghost** [guoguibing/librec#155]
I am trying to perform the following computation 

Matrix X Vector 

However, I find that the current implementation of matrix vector mulitiplication is not multithreaded.

Therefore, I tried to replace the multiplication by using public java matrix library such as "ujmp", but I found out that using ujmp is actually slower than the naive implementation as in librec.

Do you have any idea how I can make the multiplication faster?

**Comment by guoguibing** [comment]
Good suggestion to boost the computation of matrix operations. We are working on this issue as well. Multi-threading is useful if your system supports the number of threads, and you may need to take into account the fact that LibRec will create multiple threads for different folds if KCV is applied.

**Comment by ghost** [comment]
Thanks,

my question was I replaced the computation part with "ujmp", but I found that it is actually slower than the way it is implemented in librec.

So I was wondering if librec supports multithreading for matrix multiplication.

If not, do you have any idea by any chance how librec can be faster than "ujmp" ?
