### ISSUE TITLE
why socialMatrix   Produces zero for all users?????

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#156]
Hi;
i want access to trust  between users.....
for example ...trust(u1,u1)=????
my code is:
********************************************************
      for (int i = 0; i < numUsers; i++) {
            for (int j = 0; j < numUsers; j++) {
                System.out.println(socialMatrix.get(i, j));
            }
        }
        
************************************************************
But generate  the zero for all users:
0
0
0
0
0
0
0
0
0
0
0
0

**Comment by SunYatong** [comment]
@hphphphphp 
The trust relationships between users are very sparse, use this to get the non-zero values
```java
        // configuration
        conf.set("rec.recommender.similarity.key" ,"user");
        conf.set("data.appender.class" ,"social");
        conf.set("data.appender.path" ,"filmtrust/trust/trust.txt");
        Randoms.seed(1);
        // build data model
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();
        // get non-zero trust values
        SparseMatrix socialMatrix = ((SocialDataAppender) dataModel.getDataAppender()).getUserAppender();
        for (MatrixEntry me: socialMatrix) {
            int row = me.row();
            int col = me.column();
            double value = me.get();
            System.out.println("user_" + row + ", user_" + col + ", trust_value:" + value);
        }
```

**Comment by hphphphphp** [comment]
very thanks;
but....
my dataset for trust is:
******************************
1 2 1
1 3 1
2 4 1
3 1 1
3 2 1
4 3 1
4 1 1

**********************************
but generate this output:

user_459, user_460, trust_value:1.0
user_459, user_461, trust_value:1.0
user_460, user_462, trust_value:1.0
user_461, user_459, trust_value:1.0
user_461, user_460, trust_value:1.0
user_462, user_461, trust_value:1.0

**Comment by SunYatong** [comment]
@hphphphphp 
The dataset format is [userId userId trustValue]
The output format is [userIdx userIdx trustValue]
Check my code at #157 to convert userIdx to userId.
