### ISSUE TITLE
how to...access to trusters  and trustees  for one user???

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#157]
Hi;
how to...access to( trusters  and trustees)  for one user???
for example ...trusters(u1)=??    trustees(u1)=??
T+(u1)=??
T-(u1)=??

thanks;

**Comment by SunYatong** [comment]
@hphphphphp 
The API of SparseMatrix should be useful for you.
```java
        // configuration
        conf.set("rec.recommender.similarity.key" ,"user");
        conf.set("data.appender.class" ,"social");
        conf.set("data.appender.path" ,"filmtrust/trust/trust.txt");
        Randoms.seed(1);
        // build data model
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();
        // get trust matrix
        SparseMatrix socialMatrix = ((SocialDataAppender) dataModel.getDataAppender()).getUserAppender();
        System.out.println(socialMatrix.get(6, 811));
        
        int userIdx = 6;
        // out links
        int[] userOutLinks = socialMatrix.row(userIdx).getIndex();
        for (Integer i: userOutLinks) {
            System.out.println(i);
        }
        System.out.println("-----------");
        // in links
        int[] userInLinks = socialMatrix.column(userIdx).getIndex();
        for (Integer i: userInLinks) {
            System.out.println(i);
        }
```

**Comment by hphphphphp** [comment]
thanks for you....
yes...Yes Very helpful

but.......products...out links=in links

for this code output is:
1.0
////////////
811
903
993
995
-----------
811
903
993
995

**Comment by SunYatong** [comment]
@hphphphphp 
I converted the userIdx to userId to print, here is my output:
```
test userId:1056
out links: 353 445 535 537 
in links: 353 445 535 537 
```
Then I checked the input data file to find the out links and in links of user_1056:
out links:
![image](https://user-images.githubusercontent.com/17143022/26998726-db6d8946-4dba-11e7-894a-47a937a531c3.png)
in links:
![image](https://user-images.githubusercontent.com/17143022/26998811-2dc58422-4dbc-11e7-8a85-db95c6a8fa39.png)

It shows that user_1056's out links == in links.
**Note that** some userIds in trust file are not included in rating files, so the output <= the elements in trust file.
And here is my code:
```java
        // configuration
        conf.set("rec.recommender.similarity.key" ,"user");
        conf.set("data.appender.class" ,"social");
        conf.set("data.appender.path" ,"filmtrust/trust/trust.txt");
        Randoms.seed(1);
        // build data model
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();
        // get trust matrix
        SparseMatrix socialMatrix = ((SocialDataAppender) dataModel.getDataAppender()).getUserAppender();
        // get user mapping data
        BiMap<Integer, String> userIdxToUserId = dataModel.getUserMappingData().inverse();

        int userIdx = 6;
        System.out.println("test userId:" + userIdxToUserId.get(userIdx));
        // out links
        System.out.print("out links: ");
        int[] userOutLinks = socialMatrix.row(userIdx).getIndex();
        for (Integer i: userOutLinks) {
            System.out.print(userIdxToUserId.get(i) + " ");
        }
        System.out.println();
        // in links
        System.out.print("in links: ");
        int[] userInLinks = socialMatrix.column(userIdx).getIndex();
        for (Integer i: userInLinks) {
            System.out.print(userIdxToUserId.get(i) + " ");
        }
```

**Comment by hphphphphp** [comment]
Hi;
your code is fine for filmtrust...but  your code it does not work for epinions and other dataset

And here is my output for epinions :
the output is empty:

test userId:22605
out links: 
in links: 
the image for epinions :
![capture](https://user-images.githubusercontent.com/28094374/27003606-1d2a9032-4e0f-11e7-97f7-049b67467489.PNG)


also for film trust for example  useridx=8 ....Does not produce all outlinks and inlinks

**Comment by SunYatong** [comment]
@hphphphphp 
As I mentioned before, some userIds in trust file are not included in rating files, so [the output <= the elements in trust file]. **Both trust and rating files**  need to be checked if you want to verify the outputs.

- if output < real elememts, check if the missing elements' userIds are included in rating file.
- if output is empty, check if the testing userId is included in trust file

If the problem still occurs, send me your data file and I will debug the code.
My Email address: sunyatong65536@gmail.com
