### ISSUE TITLE
How to  use from Evaluators in librec for evaluate the MY Algorithm

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#158]
Hi;
I am write a new Algorithm (proposed method)  and I want use form Evaluators that  are in librec...
for example :
my algorithm in the final product a Userfactor matrix(P) and Itemfactor matrix(Q) and me add its to
userFactors and itemFactors according to :

 userFactors.add(u, k, P[u][k]);
  itemFactors.add(i, k, Q[i][k]);

is it correct????
and How to  use from Evaluators in librec for evaluate the MY Algorithm???
thanks;

**Comment by SunYatong** [comment]
@hphphphphp 
Yes, It should work correctly in your way if userFactors and itemFactors are initialized with zeros. 

To use Librec's evaluators, you need to:
- use testset splitter to read your pre-splitted  dataset.
-  implement a recommender in LibRec extending MatrixFactorizationRecommender
- read your parameters in P and Q to userFactors and itemFactors in setup function
