### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#159]
hi;
I am get error :  OutOfMemoryError: Java heap space

for dataset Epinions  and array  E

 E = new double[numUsers][numItems];

**Comment by hphphphphp** [comment]
and;
how to use from Flixster dataset??
my output product error :for flixster
ArrayIndexOutOfBoundsException

**Comment by hphphphphp** [comment]
I want dataset Ciao :
please sent to me link download;
this link do not work
http://www.public.asu.edu/~jtang20/datasetcode/truststudy.htm

**Comment by SunYatong** [comment]
@hphphphphp 

- Use Table or SparseMatrix if you want to store the rating data. Your double array will cost 44 GB ( 8 byte * 40163 * 139738 ) memory.
- Flixster data file is not suitable for librec. You have to pre-process it to fit our format.
- I Googled Ciao and the first link just works well https://www.librec.net/datasets.html. Don't be lazy please...

And Remember to close your issues if the problems are solved  ^_^
