### ISSUE TITLE
problem with epinions dataset

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#161]
hi;
 here is my code but Does not produce anything just for epinions dataset.

  Configuration conf = new Configuration();

        //	Resource resource = new Resource("rec/context/rating/trustsvd-test.properties");
//	conf.addResource(resource);
        conf.set("dfs.data.dir", "../data");

//conf.set("data.input.path", "filmtrust");
conf.set("data.input.path", "epinions");

//     conf.set("data.splitter.ratio", "rating");
//     conf.set("data.splitter.trainset.ratio", "0.8");

        
        conf.set("rec.factor.number", "10");
        conf.set("rec.iterator.maximum", "10");

             conf.set("rec.recommender.similarity.key" ,"user");
            conf.set("data.appender.class", "social");
        conf.set("data.appender.path", "test/test-append-dir");
 
    Randoms.seed(1);
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();

                    RecommenderSimilarity similarity = new PCCSimilarity();
        similarity.buildSimilarityMatrix(dataModel);

        // get similarity values
        int numUser = ((SparseMatrix)dataModel.getTrainDataSet()).numRows();
        SymmMatrix similarityMatrix = similarity.getSimilarityMatrix();

        for (int i=0; i<numUser; i++) {
            for (int j=0; j<numUser; j++) {
                System.out.println("user_" + i + ", user_" + j + ", similarity: " + similarityMatrix.get(i, j));
            }
        }

**Comment by SunYatong** [comment]
It seems that you are using the rating file of Epinions with the trust file of FilmTrust.
Try this :

```
        conf.set("data.input.path", "epinions/rating");
        conf.set("data.appender.path" ,"epinions/trust");
```
And You may wish to take advantage of our documentation and the debug tools of your IDE  ^_^
