### ISSUE TITLE
Correct comments in SparseMatrix for getRows() method

### ISSUE THREAD

**Issue by vgeek-z** [guoguibing/librec#162]
The original comment is as follows:   
    /**
     * get rows of a specific column where (row, column) entries are non-zero
     *
     * @param col column id
     * @return a list of **column** index
     */
BUT, the @return maybe "a list of **row** index" in my understanding.  Besides, I am confuse that why you put both **col** and **column** after the @param. There are some other comments like this in SparseMatrix class, however, I am not sure whether it's my misunderstanding. So I would appreciate it if you could check them. 

Thank you for LibRec.

**Comment by SunYatong** [comment]
Thank you for your feedback ^_^

- You're right. It returns a list of row index.
- "col" is the name of the parameter and "column id" is its comment. In IDE they will be colored differently like this:
![image](https://user-images.githubusercontent.com/17143022/27037340-3a75bc6e-4fba-11e7-8e68-15408db7c5f3.png)
