### ISSUE TITLE
question about trainMatrix

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#163]
hi;
I want print trainmatrix......for example ... rating user(u) to item(i)...... (u1,i3)=???
According to dataset
 here is my code :
******************************
   BiMap<Integer, String> userIdxToUserId = DM.getUserMappingData().inverse();
      
        for (MatrixEntry matrixEntry : trainMatrix) {

            String userId = userIdxToUserId.get(matrixEntry.row()); 

            String itemId = userIdxToUserId.get(matrixEntry.column());

            double realRating = matrixEntry.get();
            System.out.println("u:" + userId + "    " + "i :" + itemId + "   " + "rat :" + realRating);
        }

*******************************
my dataset is :
1 2 2
1 3 3
1 4 4
2 2 5
2 3 6
2 4 7
3 1 8
3 2 9
3 4 10
4 1 11
4 2 12
4 3 13
****************************************
and my output is 

u:1    i :1   rat :2.0
u:1    i :3   rat :4.0
u:2    i :1   rat :5.0
u:2    i :2   rat :6.0
u:2    i :3   rat :7.0
u:3    i :1   rat :9.0
u:3    i :3   rat :10.0
u:3    i :4   rat :8.0
u:4    i :1   rat :12.0
******************************
why Not true  ???

**Comment by hphphphphp** [comment]
I want get rating  for  user(u)  to item(i)....for example rat(u2,i4)==?? According to userid
and According to dataset

**Comment by hphphphphp** [comment]
also for similarity ...i want sim(u1,u2)=??  According to userid

code is :
     
  RecommenderSimilarity similarity = new PCCSimilarity();
        similarity.buildSimilarityMatrix(DM);

        // get similarity values
        int numUser = ((SparseMatrix)DM.getTrainDataSet()).numRows();
        SymmMatrix similarityMatrix = similarity.getSimilarityMatrix();

        for (int i=0; i<numUser; i++) {
            for (int j=0; j<numUser; j++) {
        String userId = userIdxToUserId.get(i); 
int a=Integer.parseInt(userId);
            String itemId = userIdxToUserId.get(j);
            int b= Integer.parseInt(itemId);
                System.out.println("user_" +a + ", user_" +b+ ", similarity: " + similarityMatrix.get(a, b));
            }
        }
        *********************************
data set is :
1 1 4
1 2 4
1 3 1
1 4 4
1 5 3
2 1 2 
2 2 1
2 3 4
2 4 2
2 5 3
3 1 3
3 2 1
3 3 3
3 4 2
3 5 1
4 1 5
4 2 4
4 3 2
4 4 0
4 5 3

***************************
output is :

user_1, user_1, similarity: 0.0
user_1, user_2, similarity: 0.0
user_1, user_3, similarity: 0.0
user_1, user_4, similarity: 0.0
user_2, user_1, similarity: 0.0
user_2, user_2, similarity: 0.0
user_2, user_3, similarity: 0.0
user_2, user_4, similarity: 0.0
user_3, user_1, similarity: 0.0
user_3, user_2, similarity: 0.0
user_3, user_3, similarity: 0.0
user_3, user_4, similarity: 0.0
user_4, user_1, similarity: 0.0
user_4, user_2, similarity: 0.0
user_4, user_3, similarity: 0.0
user_4, user_4, similarity: 0.0

**Comment by hphphphphp** [comment]
very  very thanks for you and Librec

**Comment by SunYatong** [comment]
@hphphphphp 
- When printing the trainMatrix, you convert the itemIdx with user mapping, so the output is wrong.
- To get similarity values, this works well for me:
```java
        conf.set("rec.recommender.similarity.key" ,"user");
        conf.set("data.input.path", "test/hphp_issue");
        conf.set("data.splitter.trainset.ratio", "0.9");
        Randoms.seed(1);
        // build data model
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();

        // get user mapping data
        BiMap<Integer, String> userIdxToUserId = dataModel.getUserMappingData().inverse();
        int numUser = dataModel.getUserMappingData().size();

        // build similarity
        RecommenderSimilarity similarity = new PCCSimilarity();
        similarity.buildSimilarityMatrix(dataModel);

        // get similarity matrix
        SymmMatrix similarityMatrix = similarity.getSimilarityMatrix();

        for (int i=0; i<numUser; i++) {
            for (int j=0; j<numUser; j++) {
                System.out.println("user_" + userIdxToUserId.get(i) + ", user_" + userIdxToUserId.get(j) + ", similarity: " + similarityMatrix.get(i, j));
            }
        }
```
And take full advantage of your debug tools please.
