### ISSUE TITLE
How to import Librec in my project

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#164]
Hello;
How to import Librec in my project ????  how to  use the algorithm of librec in my project???
please Explain step by step; 
thanks;
thanks;

**Comment by allenjack** [comment]
Please refer to this issue: https://github.com/guoguibing/librec/issues/116

**Comment by hphphphphp** [comment]
how to delete extra algorithm ....because I want send my algorithm to journal...
I want delete multi algorithm from Librec

**Comment by allenjack** [comment]
You don't need to delete extra algorithm. You just use maven and import
LibRec.

**Comment by hphphphphp** [comment]
what maven ???
please guid me...

**Comment by murdonson** [comment]
@hphphphphp  maven项目 直接导入项目 用maven仓库

**Comment by hphphphphp** [comment]
what maven ???
please guid me...i do not understand

**Comment by allenjack** [comment]
Please check https://github.com/guoguibing/librec/issues/116, there is an example.

**Comment by hphphphphp** [comment]
I use the librec-coe.jar which is under the 'lib' directory and me  imported to my project...
but configuration product error ;
how to solve it???
and here is my code;
![capture](https://user-images.githubusercontent.com/28094374/27147329-9e4c0f7a-5151-11e7-8412-5defee38a3c1.PNG)

**Comment by hphphphphp** [comment]
how to solve it???

**Comment by hdi-amiri** [comment]
you should add it in CLASSPATH, most IDEs do this automatically.

**Comment by hphphphphp** [comment]
please guid me step by step....
what add it to CLASSPATH??

**Comment by hdi-amiri** [comment]
https://stackoverflow.com/questions/4879903/how-to-add-a-jar-in-netbeans

http://oopbook.com/java-classpath-2/classpath-in-netbeans/

**Comment by hphphphphp** [comment]
I added librec-core-2.0.0.jar to  netbeans and added to Classpath  in windoes  ...but still not solve ...

![capture](https://user-images.githubusercontent.com/28094374/27224333-d23220be-52a9-11e7-86c7-e530d33a02af.PNG)
![w](https://user-images.githubusercontent.com/28094374/27224332-d221bbf2-52a9-11e7-92b5-57b7eeb30086.PNG)
