### ISSUE TITLE
Questions about performing k-fold cross validation

### ISSUE THREAD

**Issue by MullKun** [guoguibing/librec#166]
Hi guys, I tried to perform cross validation in order to prevent over fitting, but the result is quite weird: 
The evaluation result of first fold is always much lower than others, and others are quite similar. So I tried to find out the reason, but somehow get stuck: 

This is the code I used at the beginning:
`
public double CV(int kfold, Recommender recommender, RecommenderEvaluator evaluator, Configuration Conf, TextDataModel dataModel) throws LibrecException{	    
	    double res = 0.0;
	    DecimalFormat df = new DecimalFormat("#.######");
		df.setRoundingMode(RoundingMode.CEILING);

	    for(Integer i =1; i<=kfold; i++){
	    	Configuration conf = new Configuration();
	    	conf.set("data.splitter.cv.index",i.toString());
	    	conf.set("rec.recommender.isranking", "true");
		    conf.set("rec.recommender.similarity.key","item");
		    conf.set("data.model.splitter", "kcv");
		    conf.set("rec.neighbors.knn.number", "20");
	    	TextDataModel datamodel = new TextDataModel(conf);
	    	datamodel.buildDataModel();
	    	RecommenderContext context = new RecommenderContext(conf, datamodel);
	    	RecommenderSimilarity similarity = new CosineSimilarity();
		    similarity.buildSimilarityMatrix(datamodel);
		    context.setSimilarity(similarity);
		    ItemKNNRecommender iicf = new ItemKNNRecommender();
		    recommender.setContext(context);
		    recommender.recommend(context);
		    double temp = recommender.evaluate(evaluator);
		    precisionList.add(df.format(temp));
	    	res += recommender.evaluate(evaluator);
	    }
	    System.out.println(precisionList.toString());
	    return res/kfold;
	}
`
And the results is: 
Precision overall:0,325676
Precision List: [0,091955, 0,378505, 0,392157, 0,38162, 0,384142]

This is the code I modified:

`
public double CV(Integer kfold, Recommender recommender, RecommenderEvaluator evaluator, Configuration Conf, TextDataModel dataModel) throws LibrecException{	    
	    double res = 0.0;
	    DecimalFormat df = new DecimalFormat("#.######");
		df.setRoundingMode(RoundingMode.CEILING);

	    for(Integer i =1; i<=kfold; i++){
	    	Configuration conf = new Configuration();
	    	conf.set("data.splitter.cv.number", kfold.toString());
	    	conf.set("data.splitter.cv.index",i.toString());
	    	conf.set("rec.recommender.isranking", "true");
		    conf.set("rec.recommender.similarity.key","item");
		    conf.set("data.model.splitter", "kcv");
		    conf.set("rec.neighbors.knn.number", "10");
	    	TextDataModel datamodel = new TextDataModel(conf);
	    	datamodel.buildDataModel();
	    	
	    	RecommenderContext context = new RecommenderContext(conf, datamodel);
	    	RecommenderSimilarity similarity = new CosineSimilarity();
		    similarity.buildSimilarityMatrix(datamodel);
		    context.setSimilarity(similarity);
		    ItemKNNRecommender iicf = new ItemKNNRecommender();
		    iicf.setContext(context);
		    iicf.recommend(context);
		    double temp = iicf.evaluate(evaluator);
		    precisionList.add(df.format(temp));
	    	res += iicf.evaluate(evaluator);
	    }
`

Then the result is:
Precision overall:0,088876
Precision List: [0,090008, 0,085607, 0,091542, 0,085254, 0,091968]

The only difference between these two sections is just whether a new recommender instance is created. 

I changed different small parts of the code: modified context, modified the configuration, and all of them generates the similar result as the first one unless I create a new model in each loop. 

I checked the source code of ItemKNNRecommender and AbsctractRecommender, but it shows that the train set and test set are both from the DataModel, which means when I change the setting of configuration and execute buildDataModel() again, the train set and test set are already changed (And it does). Creating a new model should not make any difference, and I think in this case, every result is just the evaluation result of first time, though the index of the data fold changes. And if this is the reason, then it means setting the context does not work at all. Then perhaps there are some bugs in it. 

**But how can I get such result that every fist evaluation result is much lower than the others?** 

PS:
 I also tried the movielens dataset, the result looks quite normal:
[0,212619, 0,20279, 0,210796, 0,215708, 0,212419]

I don't know if the user-id and item-id have any impacts on the result, but I guess no because Librec map all ids to the indices of the matrix and the indices are used. 

Could you please help me with this result? Thank you very much. :)

**Comment by guoguibing** [comment]
+ try to set different seeds for the random class
+ try to debug if the folds were converged. 
+ try to tune parameters for different datasets.

**Comment by MullKun** [comment]
- try to set different seeds for the random class
- try to debug if the folds were converged. 
- try to tune parameters for different dataset 

Thank you professor Guo, I tune the random
