### ISSUE TITLE
How to get the PCCSimilarlity of two users

### ISSUE THREAD

**Issue by xiexiaomiao** [guoguibing/librec#169]
The user is represented by the item vector，and I want to calculate two user's PCCSimilarlity and save it in a file

**Comment by murdonson** [comment]
@xiexiaomiao  https://github.com/murdonson/CoFactor/blob/master/CoFactor.java  你看看这个有用没

**Comment by murdonson** [comment]
@xiexiaomiao  or maybe you can look at this one https://github.com/murdonson/mylibrec/blob/master/src/main/java/Soreg.java
