### ISSUE TITLE
Implementation of TrustSVD 2016

### ISSUE THREAD

**Issue by hdi-amiri** [guoguibing/librec#171]
Hi @guoguibing , I wanted to know could you please add implementation of [A Novel Recommendation Model Regularized with User Trust and Item Ratings](http://ieeexplore.ieee.org/document/7404241/) to librec?

**Comment by hdi-amiri** [comment]
It would be great if authors give at least a yes no answer ! I have asked a question in stackoverflow, It would be great if anyone can provide some answer to it.

https://stats.stackexchange.com/questions/287321/computing-partial-derivative-of-a-complex-function-against-some-variables

**Comment by guoguibing** [comment]
You may find the source codes at: https://www.librec.net/luckymoon.me/pubs.html . It is based on a previous version of LibRec.
