### ISSUE TITLE
Where is the implementation of the tensor factorization algorithm ?

### ISSUE THREAD

**Issue by BadryAtef** [guoguibing/librec#172]
Hi, 
I am using Librec for my project . but when I tried to use the 
Tensor Algorithms (BPTFRecommender and PITFRecommender) which are mentioned in the Algorithms list , I didn't  find them in the API Doc or in the implementation .. my question is where can I find them .
thanks in advance

**Comment by guoguibing** [comment]
Try FMSGD, FMALS algorithms.

**Comment by JasmineXun** [comment]
Hi,maybe I have the same problem.
when I run the command "rec -exec -D dfs.data.dir=./data -D dfs.result.dir=./result -D rec.recommender.class=bptf",then show
![image](https://user-images.githubusercontent.com/19216186/35312868-82238132-00f8-11e8-805c-9594c6c4a54f.png)

and @guoguibing ,I try to use these methods FMSGD , FMALS,then get the same Exception.
need help.
Thank you very much.
