### ISSUE TITLE
in slim algorithm,what is meaning?

### ISSUE THREAD

**Issue by Ambier** [guoguibing/librec#173]
double update = 0.0d;
                        if (regL1Norm < Math.abs(gradSum)) {
                            if (gradSum > 0) {
                                update = (gradSum - regL1Norm) / (regL2Norm + rateSum);
                            } else {
                                // One doubt: in this case, wij<0, however, the
                                // paper says wij>=0. How to gaurantee that?
                                update = (gradSum + regL1Norm) / (regL2Norm + rateSum);
                            }
                        }

update is right?how?

**Comment by nasimsonboli** [comment]
They're implementing the soft-thresholding operator in this part of the code. Here's a paper you can refer to, for details.
"Regularization Paths for Generalized Linear Models via Coordinate Descent" by J Friedman - 2009.
