### ISSUE TITLE
Can we get the model output in plain text?

### ISSUE THREAD

**Issue by hetong007** [guoguibing/librec#18]
First of all, thanks for providing such a great tool!

I was reading the manual and found the `--save-model` command, but it turns out to be saved in Java's binary format. As I am not a Java programmer but still trying to make some post-processing on the latent factors, a "save to plain text" option is definitely preferred. 

I tried to read the binary files from R/python but failed, so do you think it is possible to have it added? Thank you very much.

**Comment by guoguibing** [comment]
We designed this interface but didn't implement for all the algorithms. You may have to add some code snippets to save the model of your interest.
