### ISSUE TITLE
why diversity is NaN

### ISSUE THREAD

**Issue by hphphphphp** [guoguibing/librec#185]
hi;

I am run a ranking algorithm and config it..but  alwayws product ...recall=0 and precision=NaN and AUC=0.5 and diversity product error
![screenshot from 2017-08-08 15-37-32](https://user-images.githubusercontent.com/28094374/29069483-b193b2e6-7c2a-11e7-8f02-feb99b125435.png)

and here is my code :+1: 

       // recommender configuration
        Configuration conf = new Configuration();

        conf.set("dfs.data.dir", "../data");
   
//conf.set("data.convertor.binariza.threshold","-1.0");

conf.set("data.input.path", "filmtrust/rating");

        conf.set("rec.iterator.learnrate", "0.01");
        conf.set("rec.iterator.learnrate.maximum", "0.01");
     conf.set("rec.iterator.maximum", "100");
        conf.set("rec.user.regularization", "0.01");
        conf.set("rec.item.regularization", "0.01");

        conf.set("rec.factor.number", "10");
        conf.set("rec.learnrate.decay", "1.0");
        conf.set("rec.learnrate.bolddriver", "false");

conf.set("rec.recommender.isranking","true");

conf.set("rec.eval.enable", "true");
conf.set("rec.eval.class", "auc");
conf.set("rec.recommender.ranking.topn", "100");

     Randoms.seed(1);
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();

        RecommenderContext context = new RecommenderContext(conf, dataModel);

        System.out.println("**************************************" + "\n\n");
        

        Recommender recommender = new BPRRecommender();

        recommender.setContext(context);
        recommender.recommend(context);
        
//        RecommenderEvaluator  evaluator1 = new RMSEEvaluator();
//        RecommenderEvaluator evaluator2 = new MAEEvaluator();
        RecommenderEvaluator evaluator3 = new AUCEvaluator();
        RecommenderEvaluator evaluator4 = new RecallEvaluator();
        RecommenderEvaluator evaluator5 = new PrecisionEvaluator();
        RecommenderEvaluator  eval6=new DiversityEvaluator();
//        
//        System.out.println("RMSE:" + recommender.evaluate(evaluator1));
//        System.out.println("MAE:" + recommender.evaluate(evaluator2));
        System.out.println("AUC:" + recommender.evaluate(evaluator3));
        System.out.println("RECALL:" + recommender.evaluate(evaluator4));
        System.out.println("precision:" + recommender.evaluate(evaluator5));
            System.out.println("Diversity:" + recommender.evaluate(eval6));

**Comment by SunYatong** [comment]
@hphphphphp 
- You have to set the number of TopN before using ranking evaluators.
- And build item similarity before using diversity evaluator.

Here is my demo:
'''

       
        conf.set("rec.iterator.learnrate", "0.01");
        conf.set("rec.iterator.learnrate.maximum", "0.01");
        conf.set("rec.iterator.maximum", "100");
        conf.set("rec.user.regularization", "0.01");
        conf.set("rec.item.regularization", "0.01");
        conf.set("rec.factor.number", "10");
        conf.set("rec.learnrate.decay", "1.0");
        conf.set("rec.learnrate.bolddriver", "false");
        // build data model
        TextDataModel dataModel = new TextDataModel(conf);
        dataModel.buildDataModel();

        // build recommender context
        RecommenderContext context = new RecommenderContext(conf, dataModel);

        // build similarity
        conf.set("rec.recommender.similarities", "pcc");
        conf.set("rec.recommender.similarity.key" ,"item");
        conf.setInt("rec.recommender.ranking.topn", 10);
        RecommenderSimilarity similarity = new PCCSimilarity();
        similarity.buildSimilarityMatrix(dataModel);
        context.setSimilarity(similarity);
        context.addSimilarities("item", similarity);

        // build recommender
        conf.set("rec.neighbors.knn.number", "5");
        Recommender recommender = new BPRRecommender();
        recommender.setContext(context);

        // run recommender algorithm
        recommender.recommend(context);

        // evaluate the recommended result
        RecommenderEvaluator evaluator1 = new AUCEvaluator();
        RecommenderEvaluator evaluator2 = new DiversityEvaluator();
        evaluator1.setTopN(10);
        evaluator2.setTopN(10);
        System.out.println("AUC:" + recommender.evaluate(evaluator1));
        System.out.println("diversity:" + recommender.evaluate(evaluator2));
'''

**Comment by hphphphphp** [comment]
hello;
and very thanks ;
with your Demo...recall and presion solved.....but diversity product  NaN;...and NDCG alwayes product 1;
here is my output:

AUC:0.999635747655058
diversity:NaN................................................???????
recall:0.961562420410684
presion:0.4927200000000013
NDCG:1.0........................................................?????

**Comment by anslaity** [comment]
I have a problem with diversity also. it is always equal to (0)?!
Any suggestions?

**Comment by NimaJoorabloo** [comment]
Hi,

I check all the ways to get a result from diversity evaluator but always I got NaN. I think something is wrong. I use Librec V2 and I set TopN, use set similarity parameters, I used ranking algorithms and .....
could you please tell me what is the problem or give me a sample code that works with V2 library?
Thanks in advance.
