### ISSUE TITLE
The logic is wrong in AUCEvaluator

### ISSUE THREAD

**Issue by Trangle** [guoguibing/librec#193]
1. In the process calculate "numDroppedItems", the recomment list is cut by topK, but this variable is calculate before this cut step, which cause the less amount was deprecate total twice in the rest process
2. The type is changed from list to set, which is not logic consistent

**Comment by SunYatong** [comment]
@Trangle Thank you for your feedback.

1. the recommendList is sorted and cut by topN at function recommendRank of class AbstructRecommender, before the evaluation step.
![image](https://user-images.githubusercontent.com/17143022/31317475-34cc83da-ac74-11e7-8315-5429e68e6286.png)

2. the ```recommendListByUser``` consists of (key->value) pairs, then we use ```recommendSetByUser``` to keep the keys only.
