### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space for 2GB dataset

### ISSUE THREAD

**Issue by T-10001** [guoguibing/librec#195]
I got an OutOfMemoryError exception when trying to run recommendation on 2.07GB dataset:

>17/09/27 09:54:59 INFO TextDataConvertor: All dataset files size 2224973061
> 17/09/27 09:54:59 INFO TextDataConvertor: Now loading dataset file ydata-ymusic-user-artist-ratings-v1_0
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
>         at java.util.HashMap.resize(Unknown Source)
>         at java.util.HashMap.putVal(Unknown Source)
>         at java.util.HashMap.put(Unknown Source)
>         at com.google.common.collect.StandardTable.put(StandardTable.java:141)
>         at com.google.common.collect.HashBasedTable.put(HashBasedTable.java:55)
>         at net.librec.data.convertor.TextDataConvertor.readData(TextDataConvertor.java:258)
>         at net.librec.data.convertor.TextDataConvertor.processData(TextDataConvertor.java:156)
>         at net.librec.data.model.TextDataModel.buildConvert(TextDataModel.java:81)
>         at net.librec.data.model.AbstractDataModel.buildDataModel(AbstractDataModel.java:139)
>         at net.librec.job.RecommenderJob.generateDataModel(RecommenderJob.java:310)
>         at net.librec.job.RecommenderJob.executeRecommenderJob(RecommenderJob.java:226)
>         at net.librec.job.RecommenderJob.runJob(RecommenderJob.java:178)
>         at net.librec.tool.driver.RecDriver.run(RecDriver.java:116)
>         at net.librec.tool.driver.RecDriver.main(RecDriver.java:198)

(I changed the RecommenderJob code a bit, so the line numbers might be a bit different to your version, but basically does the same thing).

It occurred 5 hour after it began running in cmd.

Max heap space was 6.9GB at the time. How to deal with such large file sizes?

**Comment by allenjack** [comment]
Hi,

Maybe you can adjust the heap size you are using. 

Hope this link works for you. https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

Best,
Chen
