### ISSUE TITLE
Unable to import project into eclipse

### ISSUE THREAD

**Issue by ghost** [guoguibing/librec#2]
hi, 
i followed the guide and  tried to import the project into eclipse (Kepler before and Luna after),but after selecting the unzipped folder librec-v1.1 or librec.v1.0 it says that no project has been detected. 
Neither it is possible to run the jar file from command line since it gives the following error:

Exception in thread "main" java.lang.NullPointerException
    at happy.coding.io.Configer.getPath(Configer.java:41)
    at librec.main.LibRec.debugInfo(LibRec.java:248)
    at librec.main.LibRec.main(LibRec.java:70)

If i'm doing something wrong please tell me!
Thanks for the patience 
AF

**Comment by VioletViolet** [comment]
Hi. I want to run librec in netbeans but I cant. Here is the error. Help me please.
![1](https://cloud.githubusercontent.com/assets/22834888/19385207/34fd5c14-921a-11e6-9dfd-ff42ad7ed41e.PNG)
