### ISSUE TITLE
Error when running SoRec and SoReg, Loss goes to Infinity.

### ISSUE THREAD

**Issue by DungxNguyen** [guoguibing/librec#20]
I keep getting errors say Loss comes to Infinity when trying SoRec and SoReg. I attach the messages here.
![screenshot from 2015-12-04 17-21-56](https://cloud.githubusercontent.com/assets/3928909/11682943/630c1c9a-9e9a-11e5-8c3d-72c007d43ee9.png)
Do you have any idea why the results come?

**Comment by feay1234** [comment]
To avoid this problem, try to set

 max.learn.rate=0.001

Hope this helps.
