### ISSUE TITLE
Running algorithms with same parameters in parallel caused different results.

### ISSUE THREAD

**Issue by T-10001** [guoguibing/librec#202]
I ran 4 AoBPR algorithms in parallel (using SwingWorkers and making 4 separate RecommenderJobs for each) and various other algorithms in parallel (even different ones).

They seemed to result in slightly different results than when running just 1 at a time. 

This doesn't occur when running them not in parallel. And also not for when running on different instances of the program (for example, 2 instances).

Any idea why this would be the case?

**Comment by SunYatong** [comment]
@s3433557 
Different result could caused by different
- dataset splitting
- parameters initializaiton

You can debug to see where the differences come from. Make sure your configurations, especially the random seed, are the same.

**Comment by T-10001** [comment]
Dataset split and parameters are same, including the seed. 

The different results only occur when running the algorithms in parallel, but always same results when running one after another.

**Comment by SunYatong** [comment]
Hmm...I haven't confronted with this problem.  Could you please post your code here or email it to me? So I can run it and find the cause.

My email is sunyatong65536@gmail.com
