### ISSUE TITLE
Questions about dataset  preprocessing in EFMRecommender

### ISSUE THREAD

**Issue by ChenSuL** [guoguibing/librec#203]
How do you conduct data preprocessing in EFMRecommender?  Could you share the code for review sentiment analysis?   I want to run with my own data set.  Thank you!

**Comment by SunYatong** [comment]
The sentiment analysis toolkit is developed by Professor Zhang (http://yongfeng.me/), the author of EFM. You could find the code on his website or ask him for the code. My pre-process is just reformatting the dataset given by http://yongfeng.me/dataset/.

**Comment by ChenSuL** [comment]
Ok, I've got the code already. Thank you~
