### ISSUE TITLE
Predict the rating for every item a user not rated in the train set

### ISSUE THREAD

**Issue by abdollahpouri** [guoguibing/librec#204]
Hello,
I want to predict the rating for every item a user has not rated in the train set. In other words, I am not looking for a top-K items. I want all of them with their predicted ratings and store it as the userid, itemId, predicted_rating in the text file. 
Should I just set the "rec.recommender.ranking.topn" to a very large number so it put all the predicted ratings for users in the result file or I should do something more than that?

Thanks

**Comment by SunYatong** [comment]
@himanData 
Hi, just set "rec.recommender.ranking.topn" as the total number of items should work.
