### ISSUE TITLE
socialmf好像公式弄错了

### ISSUE THREAD

**Issue by murdonson** [guoguibing/librec#211]
![image](https://user-images.githubusercontent.com/20641803/32321587-8a0edca8-bffc-11e7-8622-8ae941900a48.png)

我个人觉得应该是这样啊
-regSocial *   (userFactors.get(trustedUserIdx, factorIdx) -(trustedValue / numTrusted)* sumDiffs[factorIdx] / numTrust)
按照 我那样改后 指标有一点点的提升
对不 亚童?

**Comment by SunYatong** [comment]
Hi, I checked the reference paper and found that the original implementation is the same with the paper, however your version loses "(trustedValue / numTrusted)" for "userFactors.get(trustedUserIdx, factorIdx)".

As shown in the picture below : 

![image](https://user-images.githubusercontent.com/17143022/32338167-f6e01ae0-c02e-11e7-83bb-2b6e65ce756f.png)

**Comment by murdonson** [comment]
嗯嗯 我搞错了 3q
