### ISSUE TITLE
Running librec from the command line - cannot run the timeSVD++ algorithm 

### ISSUE THREAD

**Issue by trimkaleci** [guoguibing/librec#213]
I am trying to experiment with librec from the command line, but I run into issues when I try to run timeSVD++.  I get the following error:

**_java.lang.NullPointerException[ERROR] 2017-11-07 13:06:43,743 --

[ERROR] 2017-11-07 13:06:43,743 --
        at librec.rating.TimeSVD.initModel(TimeSVD.java:138)
        at librec.intf.Recommender.execute(Recommender.java:325)
        at librec.intf.Recommender.run(Recommender.java:307)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at librec.rating.TimeSVD.initModel(TimeSVD.java:138)
        at librec.intf.Recommender.execute(Recommender.java:325)
        at librec.intf.Recommender.run(Recommender.java:307)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at librec.rating.TimeSVD.initModel(TimeSVD.java:138)
        at librec.intf.Recommender.execute(Recommender.java:325)
        at librec.intf.Recommender.run(Recommender.java:307)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at librec.rating.TimeSVD.initModel(TimeSVD.java:138)
        at librec.intf.Recommender.execute(Recommender.java:325)
        at librec.intf.Recommender.run(Recommender.java:307)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at librec.rating.TimeSVD.initModel(TimeSVD.java:138)
        at librec.intf.Recommender.execute(Recommender.java:325)
        at librec.intf.Recommender.run(Recommender.java:307)
        at java.lang.Thread.run(Unknown Source)
[ERROR] 2017-11-07 13:06:43,748 --
java.lang.NullPointerException
        at librec.main.LibRec.runCrossValidation(LibRec.java:500)
        at librec.main.LibRec.runAlgorithm(LibRec.java:400)
        at librec.main.LibRec.execute(LibRec.java:147)
        at librec.main.LibRec.main(LibRec.java:223)_**

Can anyone of you help me please? 

Thank you very much in advance!

**Comment by SunYatong** [comment]
Sorry, the 1.3 version is not supported any more. We are currently working on the 2.0.0 version and we strongly recommend you to update to 2.0.0. 

In 2.0.0, you can run algorithms both in command line and IDE with some simple configurations which are illustrated in our documentation(https://www.librec.net/dokuwiki/doku.php).

Take TimeSVD as an example:
- command line: librec rec -exec -D rec.recommender.class=timesvd -conf ../core/src/main/resources/rec/context/rating/timesvd-test.properties
- IDE: just run TimeSVDTestCase

**Comment by trimkaleci** [comment]
Hello SunYatong,

thanks a lot for your reply. It worked like that. As I am working on a project, I have to compare the results  of timeSVD++ with the results of an algorithm about item recommendation which is related to fashion data and includes additional source of information for training the model which are the image features (the algorithm is named as TVBPR+ and is presented in this [paper](https://arxiv.org/abs/1602.01585)). As it is about item recommendation, the performance of the TVBPR+ is measured using AUC (Area under the ROC curve).  Such that, I would like to ask you if I can also measure the performance of timeSVD++ using AUC, and compare the results with the AUC value of TVBPR+?

Thank you very much in advance!

**Comment by SunYatong** [comment]
To measure TimeSVD with ranking evaluators, all you have to do is to modify its configuration file by adding:
```
rec.recommender.isranking=true
rec.recommender.ranking.topn=10
```
This should work but the performance is really bad (AUC=0.502 in my test), maybe you have to tune the parameters yourself.

Additionally, if you want to convert the explicit rating feedback into implicit feedback, you have to set
```
data.convert.binarize.threshold=a non-negative integer
```

**Comment by trimkaleci** [comment]
Hello SunYatong,

Thank you very much!! It was very helpful for me! 

I have done an implementation of timeSVD++ (you can find it [here](https://github.com/leo1023/timeSVDpp/blob/master/timeSVDpp.py). I run my implementation of timieSVD++ on the same dataset as the one used on librec ( ../ratings-date.txt), but I have different result of the RMSE value. For example, when the implementation of timeSVD++ from librec is used, the RMSE value in 100 iterations is **0.921491749771918**, whereas when my implementation of timeSVD++ is used, the RMSE value in 20 iterations is **0.743524108821** .

Could you please check my implementation of timeSVD++ ([here ](https://github.com/leo1023/timeSVDpp/blob/master/timeSVDpp.py)) quickly, and let me know if there is any mistake?  
Thank you very much in advance! I really appreciate any feedback or suggestion from your side.

**Comment by SunYatong** [comment]
Hi, if you want to compare the results, you have to make sure that
- they are using the same train/test set
- the parameters are initialized in the same distribution
- the configurations are the same

I haven't read this paper yet and I am afraid I am too busy to check your code recently. But the performance of your result is really good so I guess there shouldn't be any significant error in your implementation. 

I will read the paper and your code after several examinations and deadlines (T T)

**Comment by trimkaleci** [comment]
Hi SunYatong,

Thank you very much for your reply! 

I will look forward to hear your feedback.

Thanks a lot once again!

All the best!

**Comment by Owusu1** [comment]
Pls am trying to evaluate some recommender algorithm, I HV being able to import  librec into the eclipse IDE but when running will be giving u problems like 'could not find librec.main.LibRec

**Comment by Owusu1** [comment]
Pls I need ur assistance

**Comment by allenjack** [comment]
Hi,

Could you post how you are running librec?

**Comment by Owusu1** [comment]
After downloading and importing it through file>import>project>existing project into workspace 
Then through the root directory of the unzipped source code, then finish.  The system find it difficult to locate the main class

**Comment by Owusu1** [comment]
I HV being trying to run it server.activation but still giving me problems, pls I need ur assistance

**Comment by shainaraza** [comment]
> To measure TimeSVD with ranking evaluators, all you have to do is to modify its configuration file by adding:
> 
> ```
> rec.recommender.isranking=true
> rec.recommender.ranking.topn=10
> ```
> This should work but the performance is really bad (AUC=0.502 in my test), maybe you have to tune the parameters yourself.
> 
> Additionally, if you want to convert the explicit rating feedback into implicit feedback, you have to set
> 
> ```
> data.convert.binarize.threshold=a non-negative integer
> ```

but its give null point error

**Comment by shainaraza** [comment]
When I put these two lines in the configuration
rec.recommender.isranking=true
rec.recommender.ranking.topn=10
it gives null point error
