### ISSUE TITLE
Running a single test case on Eclipse  

### ISSUE THREAD

**Issue by trimkaleci** [guoguibing/librec#218]
Hello, 

I have imported the Librec project to Eclipse, and now I want to run the timeSVDTestCase.java file. Could anyone of you please let me know what kind of running configuration I should use for running this file?  At the same time I would like to be able to debug the code, and see every step with regard to the test (see the values of the parameters when they are initialized, and also see how they change in the training process). 
 
Thank you very much in advance for any help or suggestion.

**Comment by allenjack** [comment]
There are some default configurations
in librec/core/src/main/resources/rec/context/rating/timesvd-test.properties
that you can refer.

**Comment by trimkaleci** [comment]
@allenjack Thanks for writing! I had problem with Eclipse, and that's why I couldn't run the test mentioned above. After I downloaded Eclipse again, I could run the test. Thanks!
