### ISSUE TITLE
"SparseTensor cannot be cast to SparseMatrix" Issue

### ISSUE THREAD

**Issue by ShaneColeman** [guoguibing/librec#219]
Hello,

I am having an issue which relates to the ARFF data model format / file format within LibRec.

The version of LibRec that I am using is version 2.0, which is running on the Eclipse IDE.

Within the Eclipse IDE, recommender systems are been run through the use of .properties files and the RecommenderJob class.

I created a .properties file, which for example has the name "ItemKNN-CF.properties and contains the following properties within it:

dfs.data.dir=data
dfs.result.dir=result
dfs.log.dir=log
data.input.path=movielens
data.model.format=text
data.column.format=UIR
data.convert.binarize.threshold=-1.0
data.model.splitter=ratio
data.spliter.ratio=rating
data.splitter.trainset.ratio=0.8
rec.recommender.isranking=false
rec.eval.enable=true
rec.eval.classes=mse
rec.eval.classes=rmse
rec.recommender.class=itemknn
rec.recommender.similarities=items
rec.similarity.class=pcc
rec.neighbors.knn.number=40
rec.similarity.shrinkage=2500

Here, the issue arise when the properties for the 'data.input.path' and 'data.model.format' are changed from text format to arff format (as shown belown):
data.input.path=arfftest/data.arff
data.model.format=arff

When the above properties are configured and the RecommenderJob executes the ItemKNN Recommender System (for this instance), the following Exception is thrown to 
the Eclipse IDE console (shown in the attached JPG image):
"net.librec.math.structure.SparseTensor cannot be cast to net.librec.math.structure.SparseMatrix"

I am unsure if there is a property incorrectly configured or missing from the .properties file, or if the category of recommender system is incorrect for ARFF files.

If there is any other information you require, please do not hesitate to ask.
Your help and feedback would be greatly appreciated.

![7_a](https://user-images.githubusercontent.com/16780420/33217651-afac3d08-d130-11e7-8686-8ccda6026cdb.jpg)

**Comment by SunYatong** [comment]
Hi, @ShaneColeman. Thank you for your feedback.

Only FactorizationMachineRecommender and TensorRecommender are supported by arff format. The others are supported by text format.

**Comment by ChenglongMa** [comment]
Hi, @SunYatong,
I was wondering if `FactorizationMachineRecommender` are supported by `text` format?
Or I can only convert my data file to `arff` format.
Thanks.
