### ISSUE TITLE
AoBPRRecomender execution is too inefficient

### ISSUE THREAD

**Issue by Kiteflyingee** [guoguibing/librec#220]
I have a data set of 60,000 data, the data form is user-item, only the user-item relationship, no score, but this data set “rec.iterator.maximum=30” on the AoBPR program takes 30 minutes, I think the efficiency is too low .It's Is there any place to optimize?

**Comment by SunYatong** [comment]
Hi, if the dataset doesn't contain rating column, the converting process
should throw exceptions. You'd better debug the recommender to check its
trainMatrix and testMatrix.

**Comment by Kiteflyingee** [comment]
I have debug the program.I find librec populated my dataset with a rating of 1.0,this is exactly the rating I need.Is it possible that my rating matrix is ​​too sparse and has a good solution?

**Comment by SunYatong** [comment]
Yes, if the user number is too large, AoBPR could be really slow. In each epoch it samples 100*numUser positive/negative pairs.

**Comment by Kiteflyingee** [comment]
ok，I understand，if i samples 50*numUser positive/negative pairs，whether it will have a great impact on the precision of the recommendation process?

**Comment by SunYatong** [comment]
It will cost less time for each epoch. But it might need more epoch to converge. And the result could be different. You can try it yourself.

**Comment by Kiteflyingee** [comment]
Thank you.
