### ISSUE TITLE
Get wrong RMSE result 0

### ISSUE THREAD

**Issue by YuzhouPeng** [guoguibing/librec#222]
Hi, Thanks for your librec package, but I still don't know why I get 0 RMSE when I run any kind of recommender algorithm.
I form a matrix of user-company-worked matrix that if a user worked in that company,  the value will be 1, otherwise the value will be zero. So it's a sparse matrix of 0 and 1
like this:
userid     companyid      worked
01             3                      1
10023       15                    0
2334          20                    1
![capture](https://user-images.githubusercontent.com/13601004/33370952-15131e78-d4f1-11e7-9e8e-08ea30b84a30.PNG)

I set the librec.properties
but I only got this
Can you tell me how to solve this problem? Thanks a million!
![capture1](https://user-images.githubusercontent.com/13601004/33370886-d6552672-d4f0-11e7-814f-9151621ff8b1.PNG)

**Comment by SunYatong** [comment]
Hi, the training process seems normal. You can debug the evaluator to see
what does the recommender predict.

**Comment by YuzhouPeng** [comment]
Could you please tell me how to debug the evaluator? I don't know how to debug this program

**Comment by SunYatong** [comment]
Set a breakpoint at here and debug to check the groundTruthList and recommendedList. ![image](https://user-images.githubusercontent.com/17143022/33472314-ad672130-d6ac-11e7-81e0-8bb6ba38a10b.png)
