### ISSUE TITLE
How do ranking models (like BPR) deal with rating data?

### ISSUE THREAD

**Issue by orefeng** [guoguibing/librec#224]
Hello, I have test librec's implementation of BPR. I see that it can deal with the rating data (range from 1 to 5). So I wonder how does this implementation deal with these rating data. Is it directly transform ratings into binary data (1 or 0) ? Maybe treat ratings less than 3 as 0?

**Comment by SunYatong** [comment]
Hi, you can config "data.convert.binarize.threshold" to binarize the rating
data.

**Comment by orefeng** [comment]
Thank you, it's good that i can customize the binarization. I need know some details about this implementation of BPR, but I am not good at Java. I want to know the setting of the test set. In other words, how does it generate the recommendation list in test? How does it construct the candidate item set?

**Comment by allenjack** [comment]
Hi,

The recommendation candidates are generated by the inner product of user latent factors and item latent factors of BPR. The higher the inner product value, the more likely the user will interact with the item.

**Comment by orefeng** [comment]
Yes, I know how BPR calculates the preference of a user to an item. What I want to know is how this implementation of BPR decide which item to calculate the preference. For example, some experiment may only consider the (user-item) pairs in test set, some may also consider  the (user-item) pairs which are unseen in both training and test set.

**Comment by allenjack** [comment]
It will calculate all the preference scores on all unobserved user-item
pairs, then rank the score and generate the recommendation list.
