### ISSUE TITLE
Beginner Questions

### ISSUE THREAD

**Issue by ran88dom99** [guoguibing/librec#226]
Why not convert rankings to ratings with monotonic regression or Platt calibration?

What are rMAE, rRMSE?

Does an R interface package for librec exist? 

Does a compiled end user friendly download exist and if not why not?

**Comment by SunYatong** [comment]
Hi, @ran88dom99 

1. Rating prediction and item ranking are two different tasks for recommender systems. 

2. They are used to measure the accuracy of predicted ratings.

3. No R interface so far.

4. We have upload the core package on Maven.

For more details, our document should be helpful for you.
