### ISSUE TITLE
Recommender Evaluator is zero

### ISSUE THREAD

**Issue by FotisSp** [guoguibing/librec#229]
Hello,

we followed your example and and some recommendations from past issues and we ended up with this code : 

    	Resource resource = new Resource("userknn-test.properties");

    	Configuration conf = new Configuration();
    	conf.addResource(resource);
    	conf.set("dfs.data.dir","E:\\Dropbox\\Dinos-Fwtis\\Thesis\\Code\\Recomendation\\data");
    	conf.set("dfs.input.path","filmtrust");
    	conf.set("data.column.format","UIR");
    	conf.set("data.convert.binarize.threshold","-1.0");

    	TextDataModel dataModel = new TextDataModel(conf);
    	dataModel.buildDataModel();

    	RecommenderContext context = new RecommenderContext(conf,dataModel);

    	RecommenderSimilarity similarity = new PCCSimilarity();
    	similarity.buildSimilarityMatrix(dataModel);
    	context.setSimilarity(similarity);

    	Recommender recommender = new ItemKNNRecommender();
    	recommender.setContext(context);

    	recommender.recommend(context);

    	RecommenderEvaluator evaluator = new RMSEEvaluator();
    	
    	System.out.println("RMSE:" + recommender.evaluate(evaluator));
		List<RecommendedItem> recommendedItemList = recommender.getRecommendedList();

	//    print filter result
		System.out.println("len " + recommendedItemList.size());
		BufferedWriter writer = new BufferedWriter(new FileWriter("recommendations.txt"));
		for (RecommendedItem recommendedItem : recommendedItemList) {
			writer.write(
					"user:" + recommendedItem.getUserId() + " " +
					"item:" + recommendedItem.getItemId() + " " +
					"value:" + recommendedItem.getValue() + "\n"
					);
			writer.flush();
		}
		writer.close();`

Our problem is that the evaluator always returns zero. We are working with the data with binary rating. We included both categories ( 1 and 0 ) in our data set as suggested in some other issues. Also the recommendations we get are the same as the input data. 

A small sample of our input data : 
>userId,item,rating 
9639,5,0
9639,1,0
9639,0,1
9639,8,0
9639,4,1
4031,7,0
4031,2,0
4031,10,1

Example output : 

>user:4031 item:10 value:1.0
user:6579 item:3 value:1.0

Any suggestions or help would be appreciated thanks in advance.

**Comment by SunYatong** [comment]
Hi, @FotisSp .Thanks for your feedback!

During data splitting, the 0.0 ratings will be removed, which means the training and testing sets only contain 1.0 entries. that's why UserKNN always predicts 1.0.

you can use -1.0 instead of 0 to solve this problem temporarily. We will fix this issue as soon as possible.

**Comment by FotisSp** [comment]
Okay thank you very much that was it! Problem solved
