### ISSUE TITLE
Consult whether librec 2.0 works well or not in distributed computation platform  when process big data

### ISSUE THREAD

**Issue by xhappy** [guoguibing/librec#230]
Hi

Recently, I am investigating whether librec 2.0 is suitable for distributed computation platform when to process the big data such as 1T data, but I don't capture enough materials on Official site. Could you please help to guide me or clarify whether librec 2.0 can meet my requests. 

Thanks in advance.

**Comment by SunYatong** [comment]
Hi, @xhappy. Thanks for your interest in our work.

The current 2.0 version might not meet your request. But our next version will support distributed computation with Spark.

**Comment by xhappy** [comment]
Got it, Thanks for your great work.
