### ISSUE TITLE
Save the model with command line in linux 

### ISSUE THREAD

**Issue by SupernovaTitanium** [guoguibing/librec#232]
Hey, I have already searched the issues and documents but I could not  find specific way to save the model by calling librec within terminal.
I want to extract the two matrices  that biased matrix factorization recommender used to predict the ratings. But if  I run something like 

 bin/librec rec -exec -D dfs.data.dir=./data -D dfs.result.dir=./result -D rec.recommender.class=biasedmf --save-model

I see nothing on the terminal while the process was still consuming CPU.
what should I type in shell or set the config file to correctly store the matrix factorization model or it is only possible by calling savemodel API inside of java?

Best regards, Frank.

**Comment by SunYatong** [comment]
Hi, @SupernovaTitanium Thanks for your interest in our work.

The function of loading and saving model are not completed yet both in Java API and command line API. You can implement it in AbstractRecommender to suit your requirement temporarily and call it inside of java.
