### ISSUE TITLE
socialMF implementation issue - normalizing trust value

### ISSUE THREAD

**Issue by lzhbrian** [guoguibing/librec#235]
Hi, I want to firstly thank you for your effort to build this marvelous lib !

I looked into the implementation of **socialMF**, and ended up finding some issue.

In your implementation, you assume a binary trust network (i.e. T_{u,v} = 0 or 1), so when normalizing the trust value, you directly divided each trust value with the number of trust users:
```
// for trust
double diffValue = userFactors.get(userIdx, factorIdx) - sumNNs[factorIdx] / numTrust;
// for trusted
tempUserFactors.add(userIdx, factorIdx, -regSocial * (trustedValue / numTrusted) *
                                 (userFactors.get(trustedUserIdx, factorIdx) - sumDiffs[factorIdx] / numTrust));
```
as in your code.

This works fine for the experiments of the original paper since the trust networks they have used in their experiments were also binary. However, their model can handle more than just binary trust networks, the trust value can be any value, not just 0 or 1. They just want to make sure that the regularization term that they have added are normalized (i.e. \Sigma_{v=1}^{N} T_{u, v} = 1).

And also, in your current implementation, we actually can pass in a non-binary trust value (store in `socialMatrix`) to the SocialMFRecommender, but due to the reasons stated above, the training would be wrong in this case. (i.e. sum of all normalized trust value would not be 1)

So in my opinion, either you can **assert trust value to be binary**, or you can **change the normalizing method** to dividing the trust value by **the sum of all trust values** (instead of **number of trust users**).

Hope I have made it clear. Please correct me if I have misunderstood anything.
Thanks

**Comment by SunYatong** [comment]
Hi, @lzhbrian. Thanks for your feedback.
I just fixed the problem at #238 , please check my modification in case I misunderstood your issue.

**Comment by lzhbrian** [comment]
Please see my comment on the code of that PR #238. I think there is a tiny mistake.

And also, I looked into the code again, and found another issue
In the original paper, the gradient is:
![screen shot 2018-02-07 at 11 59 39 pm](https://user-images.githubusercontent.com/12770792/35927084-c0ceddd8-0c64-11e8-8664-0a25985fde4c.png)
where in the last term, `T_{v, u}`, `T_{v, w}` are trust values from user v to user u and user w, respectively.
I think when normalizing the value, it should both be divided by the sum of all trust values by v.
But in your code (for the original code before PR #238 )
```
// those who trusted user u
SparseVector userTrustedVector = socialMatrix.column(userIdx);
int numTrusted = userTrustedVector.getCount();
for (int trustedUserIdx : userTrustedVector.getIndex()) {
    double trustedValue = socialMatrix.get(trustedUserIdx, userIdx);

    SparseVector trustedTrustVector = socialMatrix.row(trustedUserIdx);
    double[] sumDiffs = new double[numFactors];
    for (int trustedTrustUserIdx : trustedTrustVector.getIndex()) {
        for (int factorIdx = 0; factorIdx < numFactors; factorIdx++)
            sumDiffs[factorIdx] += socialMatrix.get(trustedUserIdx, trustedTrustUserIdx)
                    * userFactors.get(trustedTrustUserIdx, factorIdx);
    }

    numTrust = trustedTrustVector.getCount();
    if (numTrust > 0)
        for (int factorIdx = 0; factorIdx < numFactors; factorIdx++)
            tempUserFactors.add(userIdx, factorIdx, -regSocial * (trustedValue / numTrusted) *
                    (userFactors.get(trustedUserIdx, factorIdx) - sumDiffs[factorIdx] / numTrust));
}
```
I see `T_{v, u} = trustedValue / numTrusted`, and `T_{v, w} = sumDiffs[factorIdx] / numTrust`, which apparently do not have the same divisor.
In my opinion, they should both be divided by numTrust.

I haven't myself done the differentiation, but just a quick check that the implementation seemed not consistent with the original paper.

**Comment by SunYatong** [comment]
Yes you are right, I missed that line...
A new pull request #240 was created to fix that, thanks for your checking.
