### ISSUE TITLE
Prediction number is the same across all results

### ISSUE THREAD

**Issue by FotisSp** [guoguibing/librec#242]
I copied the code from librec github but every evaluator i tried it gives me the same evaluation across all results. Also the RMSE is always a big number for example 21.776... Any thoughts on what might be wrong ? Thanks

**Comment by zhao-json** [comment]
Could you verify if you are able to access the training data?

**Comment by allenjack** [comment]
Hi,
Could you check that the ground truth and prediction, which are passed into the evaluator, are expected?

**Comment by FotisSp** [comment]
@zhao-json yes i just tested it and the training data seems okay. 

My data set consists of (users,topics,[number of times user talk about the topic])

@allenjack if i understand correctly what you said i found a user that talked 11 times about a topic and the prediction that i got was 6.343374051452897. This is the value that i get across all the predictions.

![image](https://user-images.githubusercontent.com/32260861/36475351-051daed0-1703-11e8-95f3-cece742ca343.png)

this is a sample of the recommendations that i get.
