### ISSUE TITLE
Diversity is always 0

### ISSUE THREAD

**Issue by anslaity** [guoguibing/librec#245]
I am trying to evaluate diversity for two recommenders, namely: slim and plsa. Diversity is not giving me anything but 0. I use ranking, set the top n, and knn before using setting the evaluator settings. Any suggestions, please.

[alaCorrectness.txt](https://github.com/guoguibing/librec/files/1826350/alaCorrectness.txt)

**Comment by SunYatong** [comment]
DiversityEvaluator requires item-item similarities, i.e., you have to config:
```
rec.recommender.similarities=item
```
