### ISSUE TITLE
how to run the algorithm of mine in the console

### ISSUE THREAD

**Issue by xinzzzhou** [guoguibing/librec#249]
I developed my algorithm based on the librec. But cannot run in the console, may be cannot find the map of my algorithm.

I have already specified which configuration file to use on the command line, as well as the mapping of my algorithm in driver.class.props.

The original algorithm of librec can be run on the console.

Can anyone help me solve the problem?

**Comment by SunYatong** [comment]
Like I said before, you only modified the source code while the console executes the librec-core-2.0.0.jar file. So you have to compile your code into a new .jar file.
