### ISSUE TITLE
default predicted rating of UserKNN: global mean or user-specific mean?

### ISSUE THREAD

**Issue by taolian** [guoguibing/librec#25]
In the model UserKNN, whether the default predicted rating is global mean or user-specific mean when nns.size() == 0 or ws == 0?
[Line 103 in UserKNN.java](https://github.com/guoguibing/librec/blob/master/librec/src/main/java/librec/rating/UserKNN.java#L103)
[Line 122 in UserKNN.java](https://github.com/guoguibing/librec/blob/master/librec/src/main/java/librec/rating/UserKNN.java#L122)

There is the same issue with respect to ItemKNN: whether global mean or item-specific mean?

**Comment by guoguibing** [comment]
I didn't get what you mean. The codes are self-explained.

**Comment by taolian** [comment]
user-specific mean: a user's own average rating
item-specific mean: an item's own average rating

**Comment by guoguibing** [comment]
global mean
