### ISSUE TITLE
Running librec from Command line

### ISSUE THREAD

**Issue by abdollahpouri** [guoguibing/librec#250]
Hello ,
I am trying to run Librec using the command line. I should mention that I changed some algorithms and I added some other algorithms as well. So the code is not the original Librec jar file:
I am using the following command:

`./librec rec -exec`
But I get the following error:

`Could not find or load main class net.librec.tool.driver.Driver
`
The Driver class is a class I created myself and it is in the same directory as the RecDriver and DataDriver classes. Here is the content of my Driver class:

```

public class Driver {
    // Change this to load a different configuration file.
    public static String CONFIG_FILE =
            "conf/librec.properties";

    public static void main(String[] args) throws Exception {
        Configuration conf = new Configuration();
        String confFilePath = CONFIG_FILE;
        Properties prop = new Properties();
        prop.load(new FileInputStream(confFilePath));
        for (String name : prop.stringPropertyNames()) {
            conf.set(name, prop.getProperty(name));
        }
        System.out.println("Start");
        Randoms.seed(20161205);
        RecommenderJob job = new RecommenderJob(conf);
        job.runJob();
        System.out.print("Finished");
    }
}
```

I also modified two files in the bin folder called librec and librec.cmd and changed the RecDriver to Driver so that my Driver class becomes the first class that is run. 

Could you please let me know what I did wrong? To repeat my question, I am trying to run the Librec from the command line and I already modified some classes in the code.

**Comment by SunYatong** [comment]
Hava you modified the **librec-core-2.0.0.jar** file?

**Comment by abdollahpouri** [comment]
Not sure what you mean by modifying the librec-core-2.0.0.jar but I cloned the Librec source code and modified some classes.

**Comment by SunYatong** [comment]
After modifying the source code, you have to compile it into a new librec-core-2.0.0.jar file to replace the original one.
