### ISSUE TITLE
FISM (FISMrmse & FISMauc) Recommender Query 

### ISSUE THREAD

**Issue by ShaneColeman** [guoguibing/librec#257]
Hello,

I have a question which relates to both FISMrmse and FISMauc Recommender Systems.

Within the Algorithm List for both Recommenders, may I ask, what do the following lines for both Recommenders represent:

FISMauc Recommender 
rec.fismauc.rho=2
rec.fismauc.alpha=1.5

FISMrmse Recommender
rec.fismrmse.rho=1
rec.fismrmse.alpha=1.5

I have read the associated paper: _Kabbur S, Ning X, Karypis G. Fism: factored item similarity models for top-n recommender systems[C]//KDD. 2013_, and I am just looking for clarification to fully understand what these lines mean in relation to the paper?

If there is any other information you require, please do not hesitate to ask.
Your help and feedback would be greatly appreciated.

**Comment by allenjack** [comment]
Hi,

They are some hyper-parameters of the FISM algorithm.

**Comment by ShaneColeman** [comment]
Hi allenjack,

Thank you very much for your response.

If possible, would you be able to tell me (in relation to the FISM algorithms (FISMrmse & FISMauc) hyper-parameters) what .rho and .alpha represents.
I have read the paper associted with the FISM recommender system, and sadly cannot find any mention to these hyper-parameters. 
Would it be possible that these hyper-parameters are represented or known as something else in the paper?

Again, thank you very much for your help.

**Comment by allenjack** [comment]
Let me have a look, and reach you out later.

**Comment by ShaneColeman** [comment]
Thank you allenjack, I really appreciate it.

**Comment by allenjack** [comment]
Hi,

For alpha:
<img width="511" alt="screen shot 2018-05-20 at 9 09 11 pm" src="https://user-images.githubusercontent.com/4423102/40286142-8b8d01aa-5c72-11e8-8092-84d7d3b8abac.png">

For rho:
<img width="432" alt="screen shot 2018-05-20 at 9 10 13 pm" src="https://user-images.githubusercontent.com/4423102/40286147-99655cdc-5c72-11e8-8a14-d9ac11d57010.png">

**Comment by ShaneColeman** [comment]
Hi, allenjack,

Thank you very much taking the time to help me answer this question. I really appreciate it.

If possible, could you tell me what .rho stands for in relation to the hyper-parameter?

Again, thanks for your help
