### ISSUE TITLE
Similarity Shrinkage

### ISSUE THREAD

**Issue by taolian** [guoguibing/librec#26]
In [Section 5.2 of Herlocker 1999](http://dl.acm.org/citation.cfm?doid=312624.312682) and [Table 2 of Herlocker 2002](http://link.springer.com/article/10.1023%2FA%3A1020443909834), the significance weighting or shrinkage parameter for the similarity value takes the form of the fraction of the number of common elements and a threshold, for example, min(n/50, 1).

[Line 546 of Recommder.java](https://github.com/guoguibing/librec/blob/master/librec/src/main/java/librec/intf/Recommender.java#L546)
I am wondering whether there is any advantage of `sim *= n / (n + shrinkage + 0.0);` over `sim *= Math.min(n / (double)shrinkage, 1.0);` or other considerations here.

**Comment by guoguibing** [comment]
Just two different ways to shrink similarities.
