### ISSUE TITLE
Help with Sparse Matrix

### ISSUE THREAD

**Issue by sososa1213** [guoguibing/librec#261]
Hello,
Could anyone please help me how to use sparse matrix, I need to read Movielens 100k dataset, then run it with other algorithm.
Also, I get confused about sparse matrix, I know sparse matrix used to reduce zero value for not take memory space, but Movielens 100k dataset did not have any zero.  So could any  one help me to explain this point too.

I really appreciate help and support,

**Comment by allenjack** [comment]
Hi,
Since users can only interact with a few of items, which means users' ratings on most of the items are missing. Thus, for sparse matrix, we only store the observed ratings in the matrix and ignore the missing ratings.

**Comment by sososa1213** [comment]
Thank a-lot for the clarification.  I am using Movielens->ml-100k-> "ratings.txt in my code, so is that mean in Movielens dataset "ratings.txt" there some rating missing or there specific file have missing rating  like filmtrust->rating-> "ratings_1.txt"?
Thanks again.
