### ISSUE TITLE
跑social related algorithm 报exception

### ISSUE THREAD

**Issue by xiayank** [guoguibing/librec#278]
您好，我现在有一个问题，我想用epinions(http://www.trustlet.org/downloaded_epinions.html)这个dataset来推荐带social trust物品。

所以我把librec/data/filmtrust/rating下的txt file换成了epinions的rating.txt，把/librec/data/test/test-append-dir/trust-1.txt换成了epinions的trust.txt。

现在是可以用这个rating.txt去跑SVD++的，但是当我想去跑context下的rating算法(比如trustsvd, sorec)就会有
`Exception in thread "main" java.lang.NumberFormatException: For input string: "@�" `这样的exception. 并且之后再想去跑svd++,也会有相同的exception。很奇怪。希望能得到解答。谢谢！

**Comment by SunYatong** [comment]
你看下你的数据文件里的格式，和 librec 里内置数据集的文件格式一致么
