### ISSUE TITLE
A possible mistake in Wiki

### ISSUE THREAD

**Issue by JillWen** [guoguibing/librec#291]
While the ListwiseMFRecommender class listed in [the Algorithm list](https://github.com/guoguibing/librec/blob/3.0.0/doc/wiki/Recommender.md),I cannot find it from the source code.I'm confused whether it is supposed to be "ListRankMFRecommender"?Also,I cannot find the BNPoissMFRecommender class and the CPTFRecommender class either.

**Comment by SunYatong** [comment]
ListwiseMFRecommender and ListRankMFRecommender are the same.

BNPoissMF and CPTF are abandoned due to performance issues.

**Comment by JillWen** [comment]
> ListwiseMFRecommender and ListRankMFRecommender are the same.
> 
> BNPoissMF and CPTF are abandoned due to performance issues.

Got it,thanks a lot @SunYatong .
