### ISSUE TITLE
Incremental / online training

### ISSUE THREAD

**Issue by Rabrg** [guoguibing/librec#296]
For example, I would like to train an algorithm on all of the presently available data that I have. I constantly have an incoming stream of new data. I require an algorithm that can train on this new data, while keeping the progress of the original model (too much data to retrain the entire model from scratch every time new data arises).

Do any of the algorithms that this library implements support such "online" training?

**Comment by SunYatong** [comment]
Thanks for your attention.
Online training is not available currently. But the incremental function might be helpful for your requirements.

**Comment by Rabrg** [comment]
Thank you for the response. For my requirements incremental and online training is synonymous, and the [incremental](https://github.com/guoguibing/librec/tree/38c3d3325a9dc5e3e71a3c0d60e4db9d4ea8c814/core/src/main/java/net/librec/increment) package appears to be exactly what I'm looking for. Thanks.
