### ISSUE TITLE
librec ignores -headline on dataset w/ Unix line endings on Windows 10

### ISSUE THREAD

**Issue by Skylion007** [guoguibing/librec#32]
So I have a dataset on Windows with Unix line endings. It's a CSV with a headline so I want to of course remove the headline. Here is my line to determine how to parse the file:
`
ratings.setup=-columns 0 1 2 4 -threshold -1 --time-unit SECONDS -headline`
However, it keeps attempting to read the headline even though I've told it to ignore it. I am not sure if this has to do with the fact that the file uses Unix line endings on a Windows system, but it is rather ignoring that i have to copy a 5GB file to remove 1 line from a file. :( Regardless, if this parameter has changed the Wiki documentation needs to be updated. Otherwise, thank you so much for this awesome recommendation engine.

Also, as a side question, only some of my data in my dataset has timestamps? Can I ask librec to use only the data with timestamps or use timestamps only when they do not equal 0 (their uninitialized value).

**Comment by guoguibing** [comment]
Thanks for pointing out this issue to us. The source code relies on java "readline()" method to identify a line, which ends with "\n", "\r", or "\r\n". Check if your file fits this rule.  

For the data preprocessing, we expect our users to have data pre-processed to fit the format of LibRec. Although LibRec can do some format processing, the ability of current version has also limitation.
