### ISSUE TITLE
is it possible to publish it on Jitpack or Maven?

### ISSUE THREAD

**Issue by timgluz** [guoguibing/librec#34]
Hi,

i want to write Clojure wrapper for your library and it's difficult to set this project up as non-Java developer with Leiningen as it seems it doesnt find all the dependencies, specially `happy.coding.utils`.

Is it possible to release 1.3 on [Jitpack](https://jitpack.io/docs/) or [Maven](https://maven.apache.org/guides/mini/guide-central-repository-upload.html) ?

**Comment by guoguibing** [comment]
the package happy.coding.utils has been removed in the latest version and merged into the LibRec project itself.

**Comment by guoguibing** [comment]
You may download the jar package http://librec.net/index.html . Our team is developing the LibRec 2.0 alpha version, which will be also released to Maven for easy use.

**Comment by timgluz** [comment]
thanks!
