### ISSUE TITLE
Question about BPMF

### ISSUE THREAD

**Issue by abellogin** [guoguibing/librec#40]
First of all, thank you for this nice library, it is very interesting, and I am planning to support it through [RiVal](http://rival.recommenders.net/) in the near future.

My question is about the [BPMF code](https://github.com/guoguibing/librec/blob/master/librec/src/main/java/librec/rating/BPMF.java). I cannot find where Equation 10 from the [paper](https://www.cs.toronto.edu/~amnih/papers/bpmf.pdf) is being applied. I have the same problem with the PREA [implementation](https://github.com/jnhwkim/PREA/blob/master/src/main/java/prea/recommender/matrix/BayesianPMF.java); however, in the Matlab [code](http://www.utstat.toronto.edu/~rsalakhu/code_BPMF/bayespmf.m) provided by the authors the average seems to be there (when probe_rat_all is updated, if I am correct).

Please, let me know whether such operation is actually used in your code or why it is not needed.
Thank you in advance.

Regards,
Alejandro

**Comment by guoguibing** [comment]
It's been quite a while since our implementation is done. Allow me to take a further investigation and comparison before further comment is given.
