### ISSUE TITLE
Extending LibRec

### ISSUE THREAD

**Issue by rburke2233** [guoguibing/librec#42]
Some access control decisions seems to make LibRec harder to extend than would seem to be necessary. Making the core recommendation methods (predict, ranking) protected means that it is not possible to build a hybrid recommender (for example, one with other Recommender classes as components) without an ugly work-around. 

See the attached pair of classes. I am trying to build a UserKNN recommender that uses MostPopular as a fall-back when there are not enough neighbors. What I would like to do is to create a subclass of UserKNN with a MostPopular component as a member and just call its ranking method, but I can't. Also, I can't access the superclass's userCorrs variable, so I have compute and store the correlations twice. 

There is also no easy way to add to the list of available recommenders or the set of available evaluation measures. 

I'm curious if there is any work underway to make libRec more extensible.

[Archive.zip](https://github.com/guoguibing/librec/files/393924/Archive.zip)

**Comment by guoguibing** [comment]
Hi there, your pull-request has been merged into the master branch. We note that your codes are high-quality. Please tell us your name such that we can add you as a contributor. Thanks for your great contribution.
