### ISSUE TITLE
there is something wrong with the movielens100k dataset

### ISSUE THREAD

**Issue by louis72** [guoguibing/librec#5]
2015-01-24 20:45:15,775 [DEBUG] User amount: 943, item amount: 1682
I haven't modify the data set, item amount should be 1683.
thank you for your reply.

**Comment by guoguibing** [comment]
Go check http://files.grouplens.org/datasets/movielens/ml-100k-README.txt

On Sat, Jan 24, 2015 at 8:55 PM, louis72 <notifications@github.com> wrote:

> 2015-01-24 20:45:15,775 [DEBUG] User amount: 943, item amount: 1682
> I haven't modify the data set, item amount should be 1683.
> thank you for your reply.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guoguibing/librec/issues/5>.
>



-- 
Best Regards,
Guibing GUO

**Comment by louis72** [comment]
Thank you.
