### ISSUE TITLE
Publish via Maven?

### ISSUE THREAD

**Issue by Xyclade** [guoguibing/librec#50]
First of all, tnx for the awesome library! Is it possible to get it distributed via Maven, such that we can update more easily?

**Comment by guoguibing** [comment]
Not now, but will consider it in the new version.

**Comment by zenogantner** [comment]
Nice suggestion, this would be great!

**Comment by wangyufengkevin** [comment]
Please use it via maven as below:
<dependency>
    <groupId>net.librec</groupId>
    <artifactId>librec-core</artifactId>
    <version>2.0.0</version>
</dependency>
