### ISSUE TITLE
Obtain Pu and Qi(Computed user and item factors)

### ISSUE THREAD

**Issue by IvicaObadic** [guoguibing/librec#56]
Hi, 

Is it possible to obtain the latent factors that desribes each user and item that are computed by Matrix Factorization algorithm ? 

Many thanks in advance

**Comment by guoguibing** [comment]
Yes, it is. You may indicate "--save-model" in the configuration file. You may check the source codes of the saveModel() method in the IterativeRecommender. If you have more/less to save, you may override this method in your own recommender.
