### ISSUE TITLE
Question on SVD Recommender

### ISSUE THREAD

**Issue by saurav28** [guoguibing/librec#57]
Hi All,

I am just trying out few SVD recommender libraries using MovieLens data set.

Considering the MovieLens dataset i have a question on Librec recommendation system.

If my rating data set is like this: userid:itemid:rating

Now i want to enter the userid and recommend other items similar to his other ratings on the items.

I found predict and ranking methods in the recommender class. Here i have to enter the userid and itemid for the prediction. Is there any kind of API for which i can get the top 5 recommendation given the userid. With the existing APIs i might have to write my own logic iterating over all the itemids for the userids and returning the top kth.

cheers,

Saurav

**Comment by guoguibing** [comment]
Yes, in the current version you'll have to write your own logic to do the query. We are developing a new version with the consideration of such demands. Also contributions are welcome to enhance such functions.
