### ISSUE TITLE
Error when Running Librec

### ISSUE THREAD

**Issue by VioletViolet** [guoguibing/librec#58]
Hi. I have copied all the classes in my netbeans but when I want to run this library it says null pointer exception error. Any ideas what I should do?
![1](https://cloud.githubusercontent.com/assets/22834888/19383071/af3e8f80-920f-11e6-9df5-e0bc9dd4dfcd.PNG)

**Comment by guoguibing** [comment]
Try to git the latest source codes from GitHub

**Comment by guoguibing** [comment]
And make sure that you have properly configered a ".conf" file before your run an algorithm.

**Comment by guoguibing** [comment]
The default configuration file is "librec.conf"

**Comment by 8-chems** [comment]
I am facing the same problem, the example userKNN doesn't work with the default librec conf file.

**Comment by FotisSp** [comment]
I am facing the same problem! userKNN doesn't work with the default librec conf file and i also used my own conf file but i received `Null Pointer Exception `


>rec.similarity.class=pcc
rec.neighbors.knn.number=50
rec.recommender.class=userknn
rec.recommender.similarities=user
rec.recommender.isranking=false
rec.recommender.ranking.topn=10
rec.filter.class=generic
rec.similarity.shrinkage=10

**Comment by allenjack** [comment]
Hi,

Could you provide the full stack trace information?

**Comment by FotisSp** [comment]
yes the stack trace is : 

`Exception in thread "main" java.lang.NullPointerException
	at net.librec.recommender.cf.UserKNNRecommender.setup(UserKNNRecommender.java:52)
	at net.librec.recommender.AbstractRecommender.recommend(AbstractRecommender.java:216)
	at Thesis.Recomendation.Recommendation.main(Recommendation.java:56)`
