### ISSUE TITLE
Question about updating P, Q and W in TrustSVD algorithm

### ISSUE THREAD

**Issue by friedvan** [guoguibing/librec#6]
Hi, 
I am recently learning the TrustSVD algorithm, but I have some trouble understanding codes about updating parameter P, Q, and W in TrustSVD.java.

Here is my question:
updates of user feature matrix P and user trust matrix W are cached in PS and WS during one pass of rating and social data, so P and W are not changed during one pass of whole data. However, item feature Q, user bias vector and item bias vector are updated for every rating sample using the old user feature P instead of using updated feature in PS, this seems not what described in the paper of TrustSVD, why? am I getting the point of TrustSVD algorithm wrong?

Thanks~

**Comment by guoguibing** [comment]
It should be fine as long as it converges.
