### ISSUE TITLE
Can't run item ranking recommender

### ISSUE THREAD

**Issue by ylt1534** [guoguibing/librec#64]
Sorry to disturb you, but when I set the 'item.ranking' on, I can't get information about precision, recall as so on.

Below is what I get:
[INFO ] 2016-11-27 11:46:41,431 -- Metrics: MAE,MPE,NMAE,Perplexity,RMSE,R_MAE,R_RMSE,TestTime,TrainTime
LDA,0.000000,0.000000,NaN,-1.000000,0.000000,0.000000,0.000000,27.600000,27363.600000,,10, 2.0, 0.5, 1000, 300, 10,'00:27','00:00'

**Comment by taolian** [comment]
@guoguibing I ran into the same problem.
When I ran the demo and chose the recommender BPR, the obtained output is as follows:

`Dataset: ...demo\Datasets\FilmTrust\ratings.txt
With Setup: cv -k 5 -p on --rand-seed 1 --test-view all
Metrics: MAE,MPE,NMAE,Perplexity,RMSE,R_MAE,R_RMSE,TestTime,TrainTime
BPR,0.000000,0.000000,NaN,-1.000000,0.000000,0.000000,0.000000,139.200000,10003.000000,,0.0,10,0.01,-1.0,0.1,0.1,30,true,'00:10','00:00'`

I examined the config file named BPR.conf in the directory demo/config, the option item.ranking is turned on.
`recommender=BPR
evaluation.setup=cv -k 5 -p on --rand-seed 1 --test-view all
**item.ranking=on** -topN -1 -ignore -1`

But in the config file named librec.conf in the directory target/classes which is automatically generated when running the application in eclipse, the option item.ranking is turned off.
`ratings.setup=-columns 0 1 2 -threshold -1 --time-unit SECONDS
recommender=PMF
evaluation.setup=cv -k 5 --test-view all --early-stop RMSE
item.ranking=off -topN -1 -ignore -1`

Are the configuration options changed somewhere in the source code of a certain class like Recommender?

**Comment by taolian** [comment]
After debugging, I found that the configuration option 'metric.options' need to be specified in the configuration file.

The following is a code block in the constructor of the class Recommender. @rburke2233 
`// 2016/8/2 RB Added metric configuration
        // These are class names

        LineConfiger metricOptions = cf.getParamOptions("metric.options");
        List<String> metrics;
        boolean defaultMetrics = false;
        if ((metricOptions == null) || metricOptions.contains("--rating")) {
			metrics = Arrays.asList(MetricCollection.RatingMetrics);
			defaultMetrics = true;
		} else if (metricOptions.contains("--all")) {
			metrics = Arrays.asList(MetricCollection.AllMetrics);
			defaultMetrics = true;
        } else {
            metrics = metricOptions.getOptions("-metrics");
        }

        List<String> metricNames = new ArrayList<String>();
        for (String name : metrics) {
            // If it does not have a . separator for the class name, we assume it is one of the
            // built-in classes and append the librec class info.
            if (!name.contains(".")) {
                name = "librec.metric." + name;
            }
            metricNames.add(name);
        }

        // These are always included
        if (!defaultMetrics) {
            metricNames.add("librec.metric.TrainTime");
            metricNames.add("librec.metric.TestTime");
        }`


In order to evaluate the recommendation list in terms of various ranking metrics, we can specify the 'metric.options' in the following two ways: @ylt1534 

1. metric.options=--all
2. metric.options=-metric [a list of the class names of the metrics to be used (e.g., MetricPre5 MetricPre10 MetricRec5 MetricRec10)]

Currently, I do not know whether the option 'item.ranking=on' is used in the class or not. @rburke2233 @guoguibing

**Comment by taolian** [comment]
I downloaded the version librec-1.3, and ran the demo with the BPR algorithm. The results of two runs are as follows:
Prec@5, Prec@10, Recall@5, Recall@10, AUC, MAP, NDCG, MRR

0.413466, 0.348502, 0.402098, 0.632514, 0.928021, 0.423253, 0.529703, 0.594899

0.411361, 0.347752, 0.399229, 0.627385, 0.926732, 0.415989, 0.522316, 0.582657

Then I turned to the version librec-1.4, and ran the demo with the BRP algorithm ('metric.options=--all'). The results of two runs are as follows:

Prec@5, Prec@10, Recall@5, Recall@10, AUC, MAP, NDCG, MRR

0.410746, 0.348055, 0.394315, 0.629478, 0.960953, 0.479205, 0.642803, 0.593310

0.410518, 0.347930, 0.394475, 0.629358, 0.961472, 0.480688, 0.644041, 0.596124

**Although the results are similar in terms of Prec@5, Prec@10, Recall@5, Recall@10, and MRR, they are quite different in terms of AUC, MAP, and NDCG.**
