### ISSUE TITLE
Issue loading dataset without getting IndexOutOfBoundsException

### ISSUE THREAD

**Issue by lgrave11** [guoguibing/librec#7]
I'm using the the latest compiled executable found on the website(1.2) and I'm loading a dataset of this type,

```
3034,244,1
[...]
14234,90424,1
[...]
325535,1000,1
[...]
```

And trying to run librec through the jar with a conf set to something like this(Some details omitted, it's basically just the default config with the recommender and dataset values changed).

```
dataset.training.wins=trainData.csv
dataset.training.lins=-1

dataset.social.wins=-1
dataset.social.lins=-1

# in case you use separate testing files
dataset.testing.wins=testData.csv
dataset.testing.lins=-1

recommender=ItemKNN
```
and so on ends with the following exception:

```
[INFO ] 2015-02-24 20:11:04,707 -- Training: trainData.csv, Testing:: testData.csv.
[DEBUG] 2015-02-24 20:11:09,711 -- Dataset: {Users, Items, Ratings} = {462685, 17319, 1508677}, Scale = {1.0}
[DEBUG] 2015-02-24 20:11:10,914 -- Dataset: {Users, Items, Ratings} = {462685, 17471, 205340}, Scale = {1.0}
[DEBUG] 2015-02-24 20:11:11,112 -- Build item similarity matrix ...
[ERROR] 2015-02-24 20:11:11,446 -- 17320
java.lang.ArrayIndexOutOfBoundsException: 17320
        at librec.data.SparseMatrix.column(SparseMatrix.java:579)
        at librec.intf.Recommender.buildCorrs(Recommender.java:309)
        at librec.rating.ItemKNN.initModel(ItemKNN.java:70)
        at librec.intf.Recommender.execute(Recommender.java:209)
        at librec.main.LibRec.runTestFile(LibRec.java:285)
        at librec.main.LibRec.runAlgorithm(LibRec.java:196)
        at librec.main.LibRec.main(LibRec.java:125)
```

Would it be possible to get some more saying error messages? I think this might be because the test or training data has keys that are not found in the other, or something but I can't be sure.

**Comment by guoguibing** [comment]
Bug is fixed thanks to your comments. I've updated the release package. You may download a new one.

**Comment by lgrave11** [comment]
It is not completely obvious what you changed looking at the diffs because it shows entire files being replaced, but thank you for fixing it.

**Comment by guoguibing** [comment]
In case that we use separate training and test files, some users or items from the test file may not exist in the training file. So when retrieve such a row/column from trainMatrix, it will cause the issue.
