### ISSUE TITLE
Potential Bugs in net.librec.recommender.item.RecommendedItemList.java

### ISSUE THREAD

**Issue by taolian** [guoguibing/librec#74]
@wangyufengkevin @guoguibing 

[Line 252 in RecommendedItemList.java](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/item/RecommendedItemList.java#L252)

I think that `indexOfUserIdx[userIdx] > 0` should be `indexOfUserIdx[userIdx] >= 0`, otherwise it would return false if the recommended item list for _userIdx_ is put in the position 0 of _elementData_.

I think a line of code `elementData.set(indexOfUserIdx[userIdx], new ArrayList<ItemEntry<Integer, Double>>())` should be inserted after the code `indexOfUserIdx[userIdx] = idleIndexList.poll();` at [Line 164 in RecommendedItemList.java](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/item/RecommendedItemList.java#L164), otherwise it might cause NullPointerException at [Line 118](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/item/RecommendedItemList.java#L118) and [Line 133](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/item/RecommendedItemList.java#L133), because in the method _removeUserIdx(int userIdx)_, the positions in _elementData_ corresponding to idle indices in _idleIndexList_ have been set to null at 
[Line 208](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/item/RecommendedItemList.java#L208)
`elementData.set(index, null);`
and 
[Line 211](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/item/RecommendedItemList.java#L211)
`idleIndexList.offer(index);`.

**Comment by KeqiangWang** [comment]
Thank you for your feedback. You are right.
