### ISSUE TITLE
Potential Bugs in ItemKNNRecommender and UserKNNRecommender

### ISSUE THREAD

**Issue by taolian** [guoguibing/librec#75]
@wangyufengkevin @KeqiangWang @guoguibing

[Line 70 in ItemKNNRecommender.java](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/cf/ItemKNNRecommender.java#L70)

`SparseVector uv = trainMatrix.row(u);` should be changed to `SparseVector uv = trainMatrix.column(u);`, since it needs to compute the mean rating for each item rather than each user.
In addition, the local variable _u_ in the method _trainModel()_ tend to confuse readers though it does not cause error.

[Line 130 in ItemKNNRecommender.java](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/cf/ItemKNNRecommender.java#L130)

`sum += sim * (rate - itemMeans.get(itemIdx));` should be changed to `sum += sim * (rate - itemMeans.get(similarItemIdx));`, since it needs to subtract the mean rating of the corresponding similar item rather than that of the target item.
In addition, the local variable _itemRatingEntry_ in the method _predict_ also confuses the readers, because the value in the entry denotes the similarity between that item and the target item rather than a rating.

[Line 150 in ItemKNNRecommender.java](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/cf/ItemKNNRecommender.java#L150)

`Lists.sortList(itemSimilarityList[itemIdx], false);`
I wonder whether the second parameter should be set to **true** or **false** in order to sort the list in descending order of similarity values.

[Line 140 in UserKNNRecommender.java](https://github.com/guoguibing/librec/blob/2.0.0-RC/core/src/main/java/net/librec/recommender/cf/UserKNNRecommender.java#L140)

`Lists.sortList(userSimilarityList[userIndex], false);`
There exists the same problem as above.

In addition, the local variable _userRatingEntry_ in the method _predict_ also confuses the readers, because the value in the entry denotes the similarity between that user and the target user rather than a rating.

**Comment by KeqiangWang** [comment]
Thank you for your feedback. I will fix them.
