### ISSUE TITLE
isranking configuration

### ISSUE THREAD

**Issue by rburke2233** [guoguibing/librec#76]
I think the "isranking" configuration option is both confusing and incorrect. It conflates two conditions:

1. The data is unary, such as click-through or purchase history.
2. Item ranking is to be computed.

Note that topn is not even retrieved from the configuration file unless isranking is true.

However, it is possible and useful to compute rankings on non-unary data and this is currently not possible. For example, if isRanking is true and the data has ratings, the output of userKNN will be incorrect because it ignores the ratings. Whether the data is unary or not is a function of the data. Whether the evaluation should use ranking or not is a function of the evaluation metric. It seems they are unnecessarily coupled in the current implementation.

This parameter should be split into two. For example:

1. data.model.value=unary or rating
2. rec.eval.computeranking=true or false

**Comment by guoguibing** [comment]
isRanking is only used for evaluation, for data splitting, we use a "threashold" to determine if a rating should be converted to binary.

**Comment by rburke2233** [comment]
Then perhaps the bug is in UserKNN and ItemKNN. Here is the code from ItemKNN, UserKNN is similar. itemRatingEntry.getValue() is the similarity value between items. In the isRanking condition, this value is added to a sum across all peer items. In the non-isRanking condition, the rating is also retrieved and used to compute the sum. The "if" part of this condition only makes sense if the ratings are binary. Otherwise, the ranking you would get from using ratings and from ignoring ratings would be quite different: consider two items with similar similarities, but very different ratings, for example. It is unclear why ranking and predicting would use such different formulas unless the assumption is that ranking only takes place on binary data.

        if (isRanking) {
            double sum = 0.0d;
            for (Entry<Integer, Double> itemRatingEntry : nns) {
                sum += itemRatingEntry.getValue();
            }
            return sum;
        } else {
            // for rating prediction
            double sum = 0, ws = 0;
            for (Entry<Integer, Double> itemRatingEntry : nns) {
                int similarItemIdx = itemRatingEntry.getKey();
                double sim = itemRatingEntry.getValue();
                double rate = trainMatrix.get(userIdx, similarItemIdx);
                sum += sim * (rate - itemMeans.get(itemIdx));
                ws += Math.abs(sim);
            }

**Comment by guoguibing** [comment]
The approach for userKNN and itemKNN is different in the case of ranking and prediction. For ranking, we rank items according to their summation of item similarities. For prediction, we adopt the weighted average method.

**Comment by guoguibing** [comment]
It has nothing to do with rating values.

**Comment by rburke2233** [comment]
That means that the rating prediction and ranking are not consistent with each other within the same algorithm. For example, let's say that a user has four peers in his neighborhood. If all four of these rate item A as 1 (disliked) and two of them rate item B as 5 (liked) and other two don't rate B, the ranking algorithm will rank A above B because the sum of similarities for A is higher. If you calculated the ratings and then sorted the items, item B would be preferred. Surely, an item that all peers disliked should be last on the recommendation list and not first. 

I am coming to this issue as a teacher using LibRec in class and trying to explain how the algorithms work and the difference between ranking and rating. Both I and my students find this implementation choice confusing. It's true you can achieve efficiencies in ranking by not doing the same normalization that is required in predicting ratings; that's important to do. But it is not intuitive that setting "isRanking" to true should change the pairwise preference orderings that come out of the algorithm. 

There might be cases in which the implemented behavior is desirable (considering ratings as implicit feedback, regardless of rating value), but I think if this is the behavior you want, I think you should have a separate recommendation algorithm that implements that idea.

**Comment by guoguibing** [comment]
- UserKNN and ItemKNN are two algorithms that can be applied for both rating prediction and item recommendation.
- The implementation is derived according to the literature, not our choices. The ranking is indeed based on the summation of user similarities as suggested in the papers. It is true difference from rating prediction with the weighted average. 
- All algorithms may have their pros and cons. This algorithm works fine in most cases, but not in all cases as you exemplified.
