### ISSUE TITLE
Not able to import librec project into Workspace

### ISSUE THREAD

**Issue by trimkaleci** [guoguibing/librec#78]
Hello! 

I am writing because I am not able to import the "librec" project into Workspace in Eclipse.

I followed the instruction written on the website:
1. Check out the source code with git clone https://github.com/guoguibing/librec.git
2. Run Eclilpse, and select "File > Import > General > Existing Projects into Workspace".
3. Select "Select root directory: " and browse to the directory where your unzipped source code is stored.
4. Press "Finish", and the project is imported.

But, after trying to import, there was a warning stating that the project could not be found.

Could any of you please let me know what might be the problem of not being able to import librec? 

Thank you very much in advance! 

Best

**Comment by guoguibing** [comment]
Try import as a Maven project
