### ISSUE TITLE
using rbm recommender on 100k ML dataset gave null ratings for all users 

### ISSUE THREAD

**Issue by 8-chems** [guoguibing/librec#79]
hi i am using rbm recommender from cf rating packages, all ratings returned by this recommender are 0. this is the conf file used: 
dfs.data.dir=/home/development/datasets/movie_lens
dfs.result.dir=/home/development/datasets/movie_lens/rbm/results
dfs.log.dir=/home/development/datasets/movie_lens/rbm/log
data.input.path=u.data

rec.recommender.class=rbm
rec.iterator.learnrate=0.01
rec.iterator.learnrate.maximum=0.01
rec.iterator.maximum=100
rec.user.regularization=0.01
rec.item.regularization=0.01
rec.factor.number=10
rec.learnrate.bolddriver=false
rec.learnrate.decay=1.0

**Comment by SunYatong** [comment]
Sorry about the error. We have fixed it, please checkout the newest code.
If you expect better results please modify the values of configuration.

**Comment by zhegeliang2** [comment]
i found the rmse of rbm is worse than average model，can you show me better parameters，now my parameters is ：
rec.recommender.class=rbm
data.input.path=movielens/ml-100k/ratings.txt
rec.iterator.learnrate=0.01
rec.iterator.learnrate.maximum=0.01
rec.iterator.maximum=500
rec.user.regularization=0.01
rec.item.regularization=0.01
rec.factor.number=10
rec.learnrate.bolddriver=false
rec.learnrate.decay=1.0

**Comment by 8-chems** [comment]
@zhegeliang2 , hey, i am not working on it anymore, you should make many experiments to find the best configuration, good luck

**Comment by zhegeliang2** [comment]
sorry to interrupt you，but i found the default parameters can not work even for movielens ml-100k or filmtrust dataset。Do you mean i can acheive better performmance than average baseline model with debugging parameters？I also implement the rbm model myself，but i can not found rbm model work fine。So i ask librec for help，but the result is similar，can you get good result with rbm？

**Comment by 8-chems** [comment]
@zhegeliang2  dear, I am not working on that library right now however the main developer of this one @guoguibing  usually answer such question by saying, try your best to find the best parameters (experimentally) , cause it usually depends on the dataset, you can also take a look at the original paper to see what configurations are used, if not giving same results, it means a problem is somewhere in the code, hoping you good luck with that
