### ISSUE TITLE
what are those means? like ASYMM MPE

### ISSUE THREAD

**Issue by myeceptions** [guoguibing/librec#8]
/**
	 * Recommendation measures
	 * 
	 */
	public enum Measure {
		MAE, RMSE, NMAE, ASYMM, MPE, D5, D10, Pre5, Pre10, Rec5, Rec10, MAP, MRR, NDCG, AUC, TrainTime, TestTime
	}

expect for first three , i don't know what the others are short for.Would anybody give a clear explanation?

**Comment by wubin7019088** [comment]
you  can get answers from  resys wiki !

**Comment by myeceptions** [comment]
There are many webpages on resys wiki, i cannot find those ,for instance, D5 , Pre10, througe ”search“.

**Comment by guoguibing** [comment]
asymmetric loss (ASYMMLoss), mean prediction error (MPE);  mean average precision (MAP), normalized discounted cumulative gain (NDCG), mean reciprocal rank (MRR), area under the ROC curve (AUC), precision and recall, D@5 means diversity at 5. Will add these comments to source code.

**Comment by wubin7019088** [comment]
PEFECT
