### ISSUE TITLE
Compile failure!

### ISSUE THREAD

**Issue by jessefilipemorais** [guoguibing/librec#82]
I am with a problem during the compile my code. How  can i conect to a database?

![image](https://cloud.githubusercontent.com/assets/18447182/23290381/766db402-fa37-11e6-8170-11b5d219bbc0.png)

**Comment by guoguibing** [comment]
You need the datasets, which can be found in the source codes or downloaded in the librec.net.

**Comment by jessefilipemorais** [comment]
Ok,  very good, i did this. But now How can i exchange to my dataset?

Em 25/02/2017 09:17, "Guibing Guo" <notifications@github.com> escreveu:

**Comment by guoguibing** [comment]
http://wiki.librec.net/doku.php

**Comment by jessefilipemorais** [comment]
Soo good! Now i need print the similarity matrix, is it possible?

**Comment by haokeliu** [comment]
> Soo good! Now i need print the similarity matrix, is it possible?

Hello, how did you solve the problem of introducing database later?
