### ISSUE TITLE
Question about  HFTRecommender

### ISSUE THREAD

**Issue by zq7746** [guoguibing/librec#83]
In the operation of the HFTRecommender algorithm, I used the Amazon dataset,All dataset files size 134M, running for a long time without a result, is this because the data set is too big cause?
![hft_result](https://cloud.githubusercontent.com/assets/13678520/23338194/173819c8-fc3f-11e6-96f5-2f8a4077556a.png)

**Comment by guoguibing** [comment]
Can you try again with a small sample?

**Comment by zq7746** [comment]
I tried the 1.7M， but it was still the problem。
