### ISSUE TITLE
log4j:WARN

### ISSUE THREAD

**Issue by RecommenderTester** [guoguibing/librec#84]
![log4j](https://cloud.githubusercontent.com/assets/26040603/23339895/ba713cdc-fbe0-11e6-8161-255a68ecc722.PNG)

**Comment by wangyufengkevin** [comment]
The file log4j.properties is lost in your project according to the warning, you can add the log4j.properties file in your project. Thanks.

**Comment by doriancodes** [comment]
Hi! I would like to help with this issue :)
