### ISSUE TITLE
Hybrid recommender conf file?

### ISSUE THREAD

**Issue by ghost** [guoguibing/librec#85]
What needs to be added to the conf file to run a hybrid recommender?

dataset.ratings.wins=\\home\\manep\\librec\\librec\\demo\\Datasets\\ml-100k\\ml-100k\\u.data
dataset.ratings.lins=/home/manep/librec/librec/demo/Datasets/ml-100k/ml-100k/u.data

ratings.setup=-columns 0 1 2 -threshold -1

recommender=hybrid
evaluation.setup=cv -k 5 -p on --rand-seed 1 --test-view all
item.ranking=off -top -1 -ignore -1

output.setup=on -dir /home/manep/librec/librec/demo/Results/

**Comment by wangyufengkevin** [comment]
It's configuration of 1.3 version according to the issue, please checkout the new 2.0.0 version, Thanks.
