### ISSUE TITLE
In what are order are these metrics?

### ISSUE THREAD

**Issue by ghost** [guoguibing/librec#86]
I am trying to run rating algorithms and it just gives me values like this? Can you tell me which one is RMSE, MAE etc? 
![image](https://cloud.githubusercontent.com/assets/23300999/23382509/6a980ca0-fd10-11e6-8de3-869135455eca.png)

**Comment by guoguibing** [comment]
MAE, RMSE, NMAE, rMAE, rRMSE, MPE, configuration, training time, test time

**Comment by guoguibing** [comment]
For version 1.3, you may check out the tutorial at: http://librec.net/release/v1.3/tutorial.html. However, we strongly suggest you switched to the new version 2.0
