### ISSUE TITLE
Question about RatioDataSplitter

### ISSUE THREAD

**Issue by ChenSuL** [guoguibing/librec#87]
Is there any difference between `getRatioByRating(ratio)`  and  `getRatioByUser(ratio)` ?

**Comment by wangyufengkevin** [comment]
Thanks for your attention, the getRatioByRating(ratio) is as same as getRatioByUser(ratio) now, we'll fix on it ASAP.

**Comment by ChenSuL** [comment]
Line 242 in this file:
` if (testIndexes.contains(j)) `
I think it should be changed to
`if (testIndexes.contains(items.indexOf(j)))`
