### ISSUE TITLE
Problem when set bolddriver=true

### ISSUE THREAD

**Issue by ChenSuL** [guoguibing/librec#88]
Problems were encountered when I set `rec.learnrate.bolddriver=true` 
![image](https://cloud.githubusercontent.com/assets/18046763/23584709/6de1a482-01a4-11e7-849d-b3f6cda0f56a.png)
The parameter `delta_loss` tends to be zero !
Line 478 in AbstractRecommender.java `lastLoss = loss` in the method  `isConverged(iter)` will lead to 
Line 119 in MatrixFactorizationRecommender.java `Math.abs(lastLoss) > Math.abs(loss)` always be false.

**Comment by guoguibing** [comment]
We are aware of this issue, and will correct it soon.
