### ISSUE TITLE
TestMatrix and TrainMatrix

### ISSUE THREAD

**Issue by jessefilipemorais** [guoguibing/librec#89]
Hello, i am with adoubt, because i couldn't understand well, why is required two matrix, test and trainMatrix?

**Comment by allenjack** [comment]
Hi,

The training matrix is used to train a model, and the testing matrix is to evaluate the model.

Best,
Chen

**Comment by jessefilipemorais** [comment]
Hi my friend,

Very good! I imagined this. One more adoubt, in the algorithm provided by on site LibRec, the last part about the FILTER, 

// set id list of filter
List<String> userIdList = new ArrayList<>();
List<String> itemIdList = new ArrayList<>();
userIdList.add("20");
itemIdList.add("28");

user "20" and item "28" represents user and item already registered in the bank correct? So the algorithm will bring the recomendations of the user "20" crusades with who evaluate the item "28"? Correct?

Thanks,
Jessé

**Comment by allenjack** [comment]
Yes, your thinking is right.
