### ISSUE TITLE
The implementation of the Diversity Evaluator has a problem

### ISSUE THREAD

**Issue by abdollahpouri** [guoguibing/librec#93]
Hello,

In the diversity evaluator, you used similarity between two items instead of Dissimilarity. So, the line: 
`totalSimilarityPerUser += itemSimilarity.get(item1, item2);`
Should be:

`totalDisSimilarityPerUser += (1-itemSimilarity.get(item1, item2));`

Thanks

**Comment by guoguibing** [comment]
Thanks for pointing out this issue.

**Comment by wangyufengkevin** [comment]
We has fixed the bug, thanks for your issue.
