### ISSUE TITLE
GivenTestSetDataSplitter does not generate testMatrix correctly

### ISSUE THREAD

**Issue by abdollahpouri** [guoguibing/librec#94]
Hello,
I wanted to have my own train and test file instead of letting Librec build those files so I set the following variables in the config file:

data.input.path=data/trainset.txt
data.model.splitter=testset
data.testset.path=data/testset.txt

But in the GivenTestSetDataSplitter, the testMatrix is not created correctly. It seems both trainMatrix and testMatrix have the same number of rows and columns but my test.txt and train.txt have different number of columns (number of items)

Thanks

**Comment by LiuXiaozeeee** [comment]
set the value as follow:

data.input.path=data/trainset.txt  data/test.txt
data.model.splitter=testset
data.testset.path=data/testset.txt


test data should be included in the data.input.path

**Comment by abdollahpouri** [comment]
Are you sure you can give the path like this? 
I get this error which is actually what I was expeting to get.

`net.librec.common.LibrecException: java.nio.file.NoSuchFileException: data/trainset.txt data/testset.txt`

**Comment by LiuXiaozeeee** [comment]
The feature of setting multi paths have been completed but not available in this version. Now, you can set the **data.input.path = data** (suppose the train data and the test data are all existed in folder: **data**) and set the data.testset.path as **data/testset.txt**.

 Note that the train dataset and the test dataset should be included in the folder assigned in **data.input.path**.

**Comment by abdollahpouri** [comment]
Thanks. The problem is resolved now.
