### ISSUE TITLE
A significant bug in SparseMatrix.java

### ISSUE THREAD

**Issue by ChenSuL** [guoguibing/librec#95]
The DateSplitter always Contains this operation(for example Line 176 in RatioDateSplitter.java)
`trainMatrix.set(u, j, 0.0);`
This will cause zero to be added to the  `trainMatrix.valueSet`

Then, Line 187 in AbstractRecommender.java 
` minRate = Collections.min(trainMatrix.getValueSet());`
`minRate` will be zero! This is wrong!

So I think 
Line 325 in SparseMatrix.java
`valueSet.add(val);`
should be changed to 
```
if(val != 0)						
{
     valueSet.add(val);
}
```

**Comment by wangyufengkevin** [comment]
Thanks for your issue, we fixed the bug in new commit.
