### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by haocoder** [guoguibing/librec#97]
java.lang.NullPointerException error when reading my own configuration files of algorithms in the java program
![image](https://cloud.githubusercontent.com/assets/11597746/24081790/0a63f7b4-0cf5-11e7-97da-3e6ebba60340.png)

![image](https://cloud.githubusercontent.com/assets/11597746/24081786/0202a444-0cf5-11e7-8d2d-939b8a0ee61b.png)

**Comment by allenjack** [comment]
Hi,

The problem is in the setup() of UserKNN. I guess you did not build the
similarity matrix. You can refer to the sample code in the main page of our
Github.

If you still have this problem, please provide more piece of code and let's
see what happened.

Best,
Chen

**Comment by haocoder** [comment]
Actually, I  referred to the sample code in the main page of Github and it is right when use the relative directory to access the configuration files in the jar package.
![image](https://cloud.githubusercontent.com/assets/11597746/24086570/9a6a6288-0d4c-11e7-9754-dd8f41cbd65b.png)

thanks.

**Comment by wangyufengkevin** [comment]
I can run successfully in the jar project, maybe your project has some problems, the source code and result as below:
![image](https://cloud.githubusercontent.com/assets/16661705/24087472/695252d8-0d5a-11e7-8013-96029a8c80e6.png)
![image](https://cloud.githubusercontent.com/assets/16661705/24087477/805ce89e-0d5a-11e7-80fe-094a92a3e8e1.png)

**Comment by haocoder** [comment]
this is my project structure
![image](https://cloud.githubusercontent.com/assets/11597746/24091917/1d17db14-0d86-11e7-88bb-263d6db717c8.png)
and it's ok  in the  following red ellipse
![image](https://cloud.githubusercontent.com/assets/11597746/24091934/34723714-0d86-11e7-8aa0-50c7e6b4bd5f.png)
