### ISSUE TITLE
Running the ./librec rec -exec  command

### ISSUE THREAD

**Issue by abdollahpouri** [guoguibing/librec#99]
Hello, 
I want to run the following command but at seems that the Librec is reading from a default .properties file which I don't know where is it. There are many .properties files. Which one is the default one that librec reads from that?

./librec rec -exec  

Thanks

**Comment by LiuXiaozeeee** [comment]
.properties existed in librec/core/src/main/resources/rec/. for example asvdpp.properties is librec/core/src/main/resources/rec/cf/rating/asvdpp-test.properties. So, you can run asvdpp algorighm by **./librec rec -exec -conf ../core/src/main/resources/rec/cf/rating/asvdpp-test.properties **

**Comment by wangyufengkevin** [comment]
The properties file and parameters configuration are supported in librec. librec-default.properties is basic configuration, it's loaded  when the recommender is started, the userknn-test.properties will overwrite the librec-default.properties's configuration which is both in the librec.properties and userknn.properties.
